### ISSUE TITLE
Enable Zombie Objects for Better Debug Experience

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#100]
At rare cases when NativeScript for iOS is used with iOS APIs that involve either:

 - `addTarget:action:forControlEvents:`
 - `delegate`

Both of the property and the method hold internally a weak ref to the target. JavaScript GC however can collect the target if it is not preserved by explicit strong reference. Invoking the action or method on the delegate then results in EXC_BAD_ACCESS.

We should try to address this with good documentation article and enable zombie objects for the debug builds in the CLI.

**Comment by jasssonpet** [comment]
Zombies are never deallocated, so app memory usage can become extremely high.

**Comment by PanayotCankov** [comment]
### Use case.
[A simple camera app created with the CLI](https://github.com/PanayotCankov/camera-prematurely-collected), with the following fix un-applied: [Fixed null pointer while using camera for ios.](https://github.com/NativeScript/NativeScript/commit/ce3dfb29a8de45848670ade7da0c6210521006a4)

Will trigger the error after a few shots are taken. Just click the "Take Picture", shot a photo, and then "Use Photo" a few times.

With zombie objects you get the following hint in the console:
```
2015-05-14 10:23:43.684 TNSCamera[10442:60b] *** -[UIImagePickerControllerDelegateImpl isKindOfClass:]: message sent to deallocated instance 0x17789310
```

**Comment by fealebenpae** [comment]
Deallocated objects aren't the real culprit in this particular case. The real issue is this:
 1. Set a weak/assign property on a native object to an instance of a JavaScript-defined Objective-C class
 2. Remove all strong references to the value of the property
 3. The JavaScript garbage collector runs 
 4. The JavaScript aspect of the instance is destroyed. The native aspect is moved to the VM heap's DelayedReleaseScope
 5. In the brief moment of time before the DelayedReleaseScope is drained and the weak/assign property is not zeroed out yet, something in Objective-C messages the DelayedReleaseScope'd object
 6. The native aspect of the instance tries to call into JavaScript, but its counterpart is gone, it panics and opens a portal to a dimension of pain and EXC_BAD_ACCESS

This is fixed by keeping alive the instance in JavaScript for as long as it's needed and then manually clearing out the weak/assign property when it's no longer needed. Zombie objects not only would not help diagnose this, they would obfuscate the real issue. The correct way to go about diagnosing this would be to assert that the JavaScript aspect is alive and emit a fatal error if not.

**Comment by PanayotCankov** [comment]
Yep, we just want to help JavaScript developers easily diagnose that, we got a lot of support on this one.

**Comment by moll** [comment]
Did this get done or something? :)
