### ISSUE TITLE
Debug - Network - Post request - Request Payload will be missing 

### ISSUE THREAD

**Issue by vhristov5555** [NativeScript/ios-runtime#1072]
1. Create project 
2. Add code for post request
```
httpModule.request({
    url: "https://httpbin.org/post",
    method: "POST",
    headers: { "Content-Type": "application/json" },
    content: JSON.stringify({
        username: vm.get("user"),
        password: vm.get("pass")
    })
}).then((response) => {
    const result = response.content.toJSON();
}, (e) => {
});
```
3. Run `tns debug ios`
4. Open the URL in Chrome
5. Navigate to Network tab
6. Click on the post request
Actual: Request Payload will be missing in header section for the request.
Expected: The Request Payload to be shown `{"user":"user name","password":"password","token":"123718idjskmz"}`. This is working in android.

**Comment by mbektchiev** [comment]
The problem is caused by a hardcoded `GET` here: https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/http/http-request/http-request.ios.ts#L180

For a reference which properties need to be set look at the [Request type description](https://chromedevtools.github.io/devtools-protocol/tot/Network#type-Request) in the DevTools protocol documentation.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/NativeScript#6897
