### ISSUE TITLE
How to use NativeScript in existing iOS App

### ISSUE THREAD

**Issue by daCapricorn** [NativeScript/ios-runtime#108]
We have an App written in Objective-C already. And we try to use NativeScript in future. Is there any document introduce it? Thanks

**Comment by PanayotCankov** [comment]
Hi daCapricorn,

We can currently setup a NativeScript for iOS project to extend existing project. However I am not sure what would be the expected behavior. For sure your app has already a few iOS view controllers in place. Would you expect to keep them and extend future app versions with JavaScript? Would you expect to use the cross platform UI? Could elaborate on your scenario and what would be the happy path for you?

Regards,

**Comment by jasssonpet** [comment]
Moved to: https://github.com/NativeScript/ios-runtime/issues/459

**Comment by antonyraphel** [comment]
Hi,

I have been trying to accomplish an UIView from a NativeScript to the existing app native. This would allow a NativeScript frame to be embedded into an existing view. 

Anyone can help me out this? I'm new in this NativeScript.

Thanks!
