### ISSUE TITLE
{N} - Crash using AudioPlayerDelegate in iOS-runtime 5.2.0

### ISSUE THREAD

**Issue by KkevinLi** [NativeScript/ios-runtime#1106]
**Environment**
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.2.4 version and is up to date.
✔ Component tns-core-modules has 5.2.2 version and is up to date.
✔ Component tns-android has 5.2.1 version and is up to date.
✔ Component tns-ios has 5.2.0 version and is up to date.

**Describe the bug**
Prior to iOS-runtime 5.2.0 adding `AudioPlayerDelegate` to `AVAudioPlayer` would work, but now there will be a crash when the audio finishes playing (I suspect it has to do with `AudioPlayerDelegate.audioPlayerDidFinishPlayingSuccessfully()` as it crashes before it gets called).

 If I downgrade to 5.1.0 then `audioPlayerDidFinishPlayingSuccessfully` will be called and my application will not crash.

**To Reproduce**
Create an AVAudioPlayer and add the delegate to it. Or build the sample project below and click any of the rows which will play an audio file. After the audio file finishes the app will crash. You can test on either a simulator or device.

**Expected behavior**
Expect the callback to fire and the app to not crash.

**Sample project**
https://github.com/KkevinLi/NativescriptAudioTest

**Comment by KkevinLi** [comment]
The error is also not throwing an `uncaughtErrorEvent`.

**Comment by mbektchiev** [comment]
Hi Kevin,
I managed to reproduce the issue and it seems like somehow the delegate object is not kept alive long enough for the callback to succeed. I'm still investigating it and need some more time to find out what is the root cause. I noticed that if you move the call to `test()` immediately before calling `play()`, there's no crash. I'll write back as soon as I have more information.

**Comment by mbektchiev** [comment]
I'm still investigating it and trying to come up with a solution, but I've found the main reason for the crash. In 5.2 we've addressed a memory leak which prevented instances of JavaScript implemented classes to be deallocated. This, however, has lead to cases where native objects can be deallocated prematurely. Hopefully, a proper fix will be released with 5.3.0 or shortly after in a patch version. Meanwhile, I think I've found a workaround by manually adding a reference from some other JavaScript object which will keep the callback alive (e.g. you can ensure the delegate is kept alive by adding audioPlayer.__js_delegate = this; here https://github.com/KkevinLi/NativescriptAudioTest/blob/61927489ea5b51bc65a8d1c22d62ac947febe7b2/src/app/item/audio-player.ts#L113)

**Comment by mbektchiev** [comment]
@KkevinLi, It seems like the crash is totally expected. According to the docs [the delegate property](https://developer.apple.com/documentation/avfoundation/avaudioplayer/1387134-delegate?language=objc) is an `assign` property, meaning that it's weak and doesn't take ownership of the object. Users of this API have to keep a strong reference to it in order to keep it alive as long as it's necessary. So the _"workaround"_ that I've proposed is actually the correct way to fix the issue. Can you please try it and confirm that it's working?

I recommend reading [this article on Objective-C property attributes](https://www.ios-blog.com/tutorials/objective-c/objective-c-property-attribute-reference-guide/) for additional clarification regarding the behavior of properties, depending on the attributes applied.

**Comment by KkevinLi** [comment]
@mbektchiev I was able to get it working in my main project by created a reference to the delegate like you said, but not sure why I am unable to get it working on this demo app though. Also curious as to why this crash doesn't trigger the uncaught error event.

Regardless I will close this now as my issue is resolved. Thank you!

**Comment by mbektchiev** [comment]
I managed to make it work on the demo. I'm not sure why you weren't... But I guess it doesn't matter since it's working in the application. 

The uncaught exception handler doesn't get called because it actually isn't an exception but a `EXC_BAD_ACCESS` or a segmentation fault processor signal, which directly causes the application to crash. You can read this [nice article](https://code.tutsplus.com/tutorials/what-is-exc_bad_access-and-how-to-debug-it--cms-24544), the suggested _"Zombie objects"_ diagnostics is very useful for debugging such cases.
