### ISSUE TITLE
Question: iOS-runtime 5.3.0 changes in metadata generator's parsing of includes

### ISSUE THREAD

**Issue by KkevinLi** [NativeScript/ios-runtime#1117]
**Environment**
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.3.0 version and is up to date.
⚠ Update available for component tns-core-modules. Your current version is 5.2.2 and the latest available version is 5.3.1.
⚠ Update available for component tns-android. Your current version is 5.2.1 and the latest available version is 5.3.0.
⚠ Update available for component tns-ios. Your current version is 5.3.0 and the latest available version is 5.3.1.

**Describe the Issue**
Did something change in 5.3.0 which alters the way we interact with custom iOS plugins/frameworks?

Prior to 5.3.0 I can call my ObjC classes directly (after generating the declaration file) like `Test.func()` but now I will get `ERROR ReferenceError: Can't find variable: Test`

In addition, now when I run `TNS_TYPESCRIPT_DECLARATIONS_PATH="$(pwd)/typings" tns build ios` to generate the declaration file its empty (with the exception of the version number variables).

**Comment by mbektchiev** [comment]
Hi @KkevinLi. We have some changes which might affect the generation of metadata. Can you provide us with exact steps to reproduce the issue, so that we investigate what might have gone wrong? It's expected that plugins with native code continue to be callable from JS as before.

**Comment by KkevinLi** [comment]
Hi @mbektchiev. I create a cocoa touch framework -> make some dummy files and build the framework -> drop it into the project -> generate typings and I am able to call from JS. In 5.3.1, the types do not generate like expected and the native code cannot be referenced.

I made a small project to replicate the issue (it's built with 5.2.0 to show the expected behavior). You can go to demo and `tns run iOS` to see it working in 5.2.0 and then update to 5.3.1 and the application will run into the error above. 

I have also included the test framework under theplugin/TestingRuntime.

**Comment by mbektchiev** [comment]
Hi Kevin, I managed to make the plugin work with the new runtime by either changing the import of `Dummy.h` from angular brackets to quotes [here](https://github.com/KkevinLi/TestingRuntimePluginBug/blob/master/src/platforms/ios/TestingRuntime.framework/Headers/TestingRuntime.h) and [here](https://github.com/KkevinLi/TestingRuntimePluginBug/blob/master/theplugin/TestingRuntime/TestingRuntime/TestingRuntime.h#L19) or by changing it to 
```Objective-C 
#import <TestingRuntime/Dummy.h>
 ```

In tns-ios@5.3.0 we have upgraded the LLVM version used by the metadata generator from 4.0.0 to 7.0.0 and this seems to have imposed stricter rules for `include` and `import` directives. I'll investigate to see if it will be possible to relax them. 

For now, I'd recommend to follow the guidelines for `#include` and `#import`:
* When including a header file from some framework use   
```Objective-C
#include <Framework_name/Header_filename.h>
#import <Framework_name/Header_filename.h>
```
(refs https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Tasks/IncludingFrameworks.html)
* When including a header file which is in the same directory or some other relative directory which is not added to `HEADER_SEARCH_PATHS`, use quotes

**Comment by KkevinLi** [comment]
Thank you that fixed it! I will close this ticket now.

**Comment by mbektchiev** [comment]
I've made some improvements in the metadata generation debugging process with: https://github.com/NativeScript/ios-runtime/pull/1119 and https://github.com/NativeScript/ios-runtime/pull/1122 which are still undocumented, but documentation will follow. 

In general, the first one increases the visibility of the fact that metadata generator's stderr output is redirected to a file and it's location is `platforms/ios/build/<configuration>-<target>/metadata-generation-stderr-<arch>.txt`. And the second adds a new environment variable (`TNS_DEBUG_METADATA_STRICT_INCLUDES`) for controlling the metadata generator that can be used alongside `TNS_DEBUG_METADATA_PATH`. When it's set to `true`, `#include` errors coming due to the upgraded LLVM lib will be logged in the `metadata-generation-stderr-<arch>.txt` log file. The drawback of enabling this option is that some 3rd party Pod libraries could cause significantly less metadata being parsed and generated, so it really should be used only when debugging issues with missing metadata.
