### ISSUE TITLE
iOS runtime 5.2+ stop transfer push notification from native code to JS interface

### ISSUE THREAD

**Issue by tdhman** [NativeScript/ios-runtime#1118]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.3.1
 - Cross-platform modules: 5.3.1
 - iOS Runtime: 5.2.+
 - Android Runtime (if applicable):
 - Plugin(s): N/A
 - NativeScript-Vue 2.2.0

**Describe the bug**
I'm using PushKit to receive VoiP push notification. I register the push notification function in my appDelegate function `applicationDidFinishLaunchingWithOptions`. Before, the push token is created & my app was able to receive & display the push notification. However, since I updated the tns runtime for iOS  to the version `tns-ios@5.2.+`, my application does not receive push notification any more.

Hence to understand the problem, I tested my application with different tns runtime version. In version 5.0.0 / 5.1.0, it works fine. The problem only occurs from the version 5.2.+

**To Reproduce**
- Create a valid VoIP certificate in Apple dev console.
- Download the test project below, open `package.json` to change the appId to the one that registered with the VoIP certificate above.
- Open the application to get the push token.
- Use any program that supports to send push notification to iOS application, e.g. houston command line: https://github.com/nomad/houston

**Expected behavior**
- Push notification is received & displayed by an alert dialog.

**Sample project**
Link to test project: https://github.com/tdhman/ns-push-test

**Additional context**

**Comment by mbektchiev** [comment]
Hi @tdhman, thank you for reporting this issue. Indeed with tns-ios version 5.2.0 the code has stopped working. The reason for this is that we've fixed a memory leak in {N} which your code has relied on to work.

What happens is this: the delegate that you are assigning to `PKPushRegistry.delegate` is not kept alive by anything and it's destroyed as soon as the JS garbage collector is run for the first time since its creation. The reason is that no variable refers to it anymore (you have stored it in a local variable which has gone out of scope [here](https://github.com/tdhman/ns-push-test/blob/master/app/main.js#L173)). One could argue that you've also assigned it to `voipRegistry.delegate` but it in fact this doesn't keep it alive because according to the [documentation](https://developer.apple.com/documentation/pushkit/pkpushregistry/1614468-delegate?language=objc) the property is actually `weak`, meaning that it doesn't take ownership of the object.

One way to bind its lifetime with the application is to assign it to a JS field in you `AppDelegate` object, i.e. change 
```JS
let pkPushRegistryDelegate = new PKPushRegistryDelegateImpl()
```
to
```JS
this.pkPushRegistryDelegate = new PKPushRegistryDelegateImpl()
```

**Comment by tdhman** [comment]
Hello @mbektchiev, 

Thank you for this clear explanation. I tried what you have suggested by setting the delegate variable to global & it works. I would notice this strong / weak reference in JS from now on to avoid this kind of issue. Thanks a lot.
