### ISSUE TITLE
NSInvalidArgumentException, reason: GUL_UIApplicationDelegateImpl

### ISSUE THREAD

**Issue by NeriCodec** [NativeScript/ios-runtime#1184]
**Environment**
`package.json`:

> {
>   "nativescript": {
>     "id": "ar.waisoft.sampayo",
>     "tns-android": {
>       "version": "6.0.0"
>     },
>     "tns-ios": {
>       "version": "6.0.1"
>     }
>   },
>   "description": "NativeScript Application",
>   "license": "SEE LICENSE IN <your-license-filename>",
>   "repository": "<fill-your-repository-here>",
>   "dependencies": {
>     "@angular/animations": "~8.0.0",
>     "@angular/common": "~8.0.0",
>     "@angular/compiler": "~8.0.0",
>     "@angular/core": "~8.0.0",
>     "@angular/forms": "~8.0.0",
>     "@angular/http": "~8.0.0-beta.10",
>     "@angular/platform-browser": "~8.0.0",
>     "@angular/platform-browser-dynamic": "~8.0.0",
>     "@angular/router": "~8.0.0",
>     "nativescript-angular": "~8.0.0",
>     "nativescript-block-ui": "^1.0.0",
>     "nativescript-fancyalert": "^3.0.8",
>     "nativescript-localstorage": "^2.0.0",
>     "nativescript-mercadopago-px": "^1.1.5",
>     "nativescript-plugin-firebase": "^9.0.4",
>     "nativescript-theme-core": "^1.0.6",
>     "nativescript-toast": "^2.0.0",
>     "nativescript-ui-listview": "^7.0.1",
>     "reflect-metadata": "~0.1.12",
>     "rxjs": "~6.5.0",
>     "tns-core-modules": "~6.0.0",
>     "zone.js": "~0.9.1"
>   },
>   "devDependencies": {
>     "@angular/compiler-cli": "~8.0.0",
>     "@ngtools/webpack": "~8.0.0",
>     "nativescript-dev-webpack": "~1.0.0",
>     "node-sass": "^4.12.0",
>     "typescript": "~3.4.0"
>   },
>   "gitHead": "f28dbc60d74dd2cef4b645afd8fdd63bbb12c73e",
>   "readme": "NativeScript Application"
> }

 - CLI: 6.0.0
 - Cross-platform modules:
 - iOS Runtime: YES
 - Android Runtime (if applicable): NO
 - Plugin(s): nativescript-mercadopago-px

**Describe the bug**

When I run the **nativescript-mercadopago-px** plugin in the example everything works fine, but when I try to use it in my application, the plugin was run but it ends up closing the app

`
-[GUL_UIApplicationDelegateImpl-390FB4A5-51F3-4449-9CF3-3A3557105BE1 window]: unrecognized selector sent to instance 0x2828f0700
*** JavaScript call stack:
(
0   UIApplicationMain@[native code]
1   _start@file:///node_modules/tns-core-modules/application/application.js:277:0
2   run@file:///node_modules/tns-core-modules/application/application.js:305:0
3   bootstrapNativeScriptApp@file:///node_modules/nativescript-angular/platform-common.js:205:0
4   bootstrapApp@file:///node_modules/nativescript-angular/platform-common.js:106:0
5   bootstrapModule@file:///node_modules/nativescript-angular/platform-common.js:90:0
6   ./main.ts@file:///app/bundle.js:536:116
7   __webpack_require__@file:///src/webpack/bootstrap:74:0
8   checkDeferredModules@file:///src/webpack/bootstrap:43:0
9   webpackJsonpCallback@file:///src/webpack/bootstrap:30:0
10  anonymous@file:///app/bundle.js:2:61
11  evaluate@[native code]
12  moduleEvaluation@:1:11
13  promiseReactionJob@:1:11
)
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[GUL_UIApplicationDelegateImpl-390FB4A5-51F3-4449-9CF3-3A3557105BE1 window]: unrecognized selector sent to instance 0x2828f0700'
*** First throw call stack:
(0x205dc298c 0x204f9b9f8 0x205cdf1c8 0x2326f2220 0x205dc7ed0 0x205dc9e6c 0x1010fb1a4 0x1010fb334 0x205d33a28 0x205d339f4 0x205d32ee8 0x205d32b94 0x205cac474 0x205d32644 0x20671b6f4 0x2324d6378 0x2324d8e44 0x232b5225c 0x232b52708 0x2324d893c 0x2324df784 0x2324d7fac 0x232551280 0x23254a804 0x2326f5a00 0x2326f16e4 0x232b4887c 0x2329ad434 0x1023f6980 0x1023f7a54 0x232122a20 0x232123384 0x232086244 0x23207b640 0x232145f24 0x2321561f4 0x232b51d1c 0x232b28a74 0x232b29048 0x232b290e8 0x20a3113c8 0x2058017d4 0x2057af008 0x205d5432c 0x205d4f264 0x205d4e7c0 0x207f4f79c 0x2326c6c38 0x101f1c044 0x101f19780 0x101f1927c 0x1013bcf54 0x101f18488 0x101f16804 0x101f16804 0x101f16804 0x101f16804 0x101f16804 0x101f16804 0x101f16804 0x101f16804 0x101f16764 0x101f16804 0x101f022ac 0x1<\M-b\M^@\M-&>
`

**Expected behavior**
https://github.com/NeriCodec/nativescript-mercadopago-px/tree/master/demo-angular

**Comment by mbektchiev** [comment]
@NeriCodec Can you please provide more information about how we can reproduce the issue. It looks like the crash is related to the code in your `AppDelegate` implementation, which seems to lack the [window property](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623056-window?language=objc).

**Comment by NeriCodec** [comment]
Hello @mbektchiev 

Yes, I have the code here where it fails https://drive.google.com/open?id=1YX_Rzw9Yt_i7KiWt6mQeUmFhF6VoAOz2

**Comment by mbektchiev** [comment]
I've reproduced the crash and found out the issue is caused by having both Firebase and MercadoPago plugins:
* The Firebase plugin adds an app delegate [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/src/firebase.ios.ts#L296)
* One of MercadoPago's CocoaPod dependencies has this method in its `platforms/ios/Pods/MLUI/LibraryComponents/MLSnackBar/classes/MLSnackbar.m`:
```Objective-C
- (UIWindow *)window
{
	return [[[UIApplication sharedApplication] delegate] window];
}
```

It unconditionally calls the delegate's `window` method, which is `@optional` and should be called only if the delegate implements it. In this case, it doesn't and hence the call throws the exception you're reporting. 

As a workaround, you can either implement the `window` method and I recommend that you request the authors of the library to fix their code.

**Comment by NeriCodec** [comment]
@mbektchiev Thank you very much, but how could I do this in my plugin?

`As a workaround, you can either implement the window method and I recommend that you request the authors of the library to fix their code.`

**Comment by mbektchiev** [comment]
I meant in the app. I don't recommend that you modify the app delegate in your plugin. You can advise any users of the plugin who are facing the issue to do this in their apps.

**Comment by NeriCodec** [comment]
Since they should add the delegate in their mobile applications, it would be helpful to find out

**Comment by NeriCodec** [comment]
@mbektchiev some clue ?

**Comment by svpasumarthy** [comment]
Please refer to this app.js file. you will need to implement the following delegate in order to secure the window.

var application = require("tns-core-modules/application");
var firebase = require("nativescript-plugin-firebase");
firebase.init({}).then((instance) => {
console.log("[] Firebase was successfully initialised");}, (error) => {
console.log("[] we've an initialization error: " + error);});

var appDelegate = UIResponder.extend({
get window() {
return this._window;
},
set window(aWindow) {
this._window = aWindow;
}
}, {
protocols: [UIApplicationDelegate]
});
application.ios.delegate = appDelegate;

application.run({ moduleName: "app-root" });

**Comment by NeriCodec** [comment]
@svpasumarthy thanks man, this solution work fine !!!....
