### ISSUE TITLE
The bundle does not appear to be a dynamic framework

### ISSUE THREAD

**Issue by Nevaan** [NativeScript/ios-runtime#1187]
Hi,

I am having problem with integrating 3rd party framework into my nativescript + angular app. I am using most recent versions (Angular 8 & Nativescript 6). 

I tried to do this by importing framework from CocoaPods (example here: https://github.com/Nevaan/nativescript-dotpay-ios-sdk-showcase/tree/podfile-attempt ). In this case app builds correctly, but I cannot generate typings for imported SDK nor access framework objects from my project.

SDK provider shares also the whole *.framework directory, so I tried this way - I placed this in /platforms/ios directory, but in that case project throws errors in compile phase (https://github.com/Nevaan/nativescript-dotpay-ios-sdk-showcase/tree/unmodified-sdk-source) 
```
The bundle at $PROJECT/node_modules/nativescript-tns-dotpay/platforms/ios/DotPaySDK.framework does not appear to be a dynamic framework.
```

I tried to add module.modulemap file, in root /platforms/ios directory and in /platforms/ios/DotPaySDK.framework/Modules containing this;
```
framework module DotPaySDK {
  umbrella header "DotPaySDK.h"

  export *
  module * { export * }
}
``` 
But the same error occurs. 

After adding --log trace flag and diving into stacktrace, I've found that it breaks because of SDK's Info.plist entry - CFBundlePackageType set to BNDL. I tried to change it manually to FMWK (value expected by tns) but I guess that this is not the way to do this properly, and after doing this application complains about missing dependencies (https://github.com/Nevaan/nativescript-dotpay-ios-sdk-showcase/tree/modified-sdk-source). 

None of my attempts is generating typings for my SDK with this command:
```
TNS_TYPESCRIPT_DECLARATIONS_PATH="$(pwd)/typings" tns build ios
```  

Just in case, I also created repo based on plugin seed - https://github.com/Nevaan/nativescript-dotpay - but errors remains the same.

Do anyone know what is the issue and how to fix this?

Related stackoverflow question: https://stackoverflow.com/questions/57460922/using-3rd-party-native-sdk-in-nativescript-project-framework-does-not-appear

**Comment by mbektchiev** [comment]
Hi @Nevaan,  I've modified the plugin so that it exposes the API to NativeScript. You can see what I had to do in the PR I've opened to your repository: https://github.com/Nevaan/nativescript-dotpay/pull/1

Since the `DotPaySDK.framework` bundle hasn't got the right `Info.plist` I had to modify it. In order to be able to use it directly as a CocoaPod instead of embedding it in your plugin in the future, I'd suggest that you ask the SDK's authors to include a `module.modulemap` file, like the one you've made (and I've committed in the PR) and modify the `CFBundlePackageType` to `FMWK` which is actually the correct bundle type for frameworks, according to Apple's documentation (https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundlepackagetype?language=objc)

**Comment by Nevaan** [comment]
Wow, so it looks like I was quite close to the solution... I confirm that this is the way to solve this problem (also, typings are generated) - I will contact authors about CFBundlePackageType. I was not convinced to idea of manually modifying Info.plist file, but I believe that this is SDK's authors fault. 

Also, I will try to develop plugin-wrapper for iOS and Android and submit it to nativescript marketplace. Thank you @mbektchiev for your help!
