### ISSUE TITLE
3rd party static libraries: Google Maps SDK for iOS

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#141]

**Comment by PanayotCankov** [comment]
[We now have an example here: github.com/NativeScript/sample-iOS-StaticLibs](https://github.com/NativeScript/sample-iOS-StaticLibs).

**Comment by vijaysharm** [comment]
It looks like this example repo was removed. Any other examples available on how to add a static library through a nativescript plugin?

**Comment by ivanbuhov** [comment]
@vijaysharm Check out the [`nativescript` plugin docs](https://docs.nativescript.org/plugins/plugin-reference#directory-structure). In few words you should have the following directory structure:

```
my-plugin/
├── ...
└── platforms/
    ├── ios/
        ├── MyStaticiOSLibrary.a
        └── include/
            └── MyStaticiOSLibrary/
                └── ...
```

**Comment by vijaysharm** [comment]
Thanks @ivanbuhov, I'll take a look at the link. do i need to include the module map file as well?

**Comment by ivanbuhov** [comment]
@vijaysharm No. The NativeScript CLI will generate default on which most of the cases works out of the box.

**Comment by vijaysharm** [comment]
Thanks for your help @ivanbuhov, this worked in-so-far as I was able to see my iOS library get built as part of the app. I ran into compilation failures because the static libraries has dependencies on AVFoundation and SystemConfiguration. I edited my [build.xcconfig](http://docs.nativescript.org/plugins/plugin-reference#buildxcconfig-specification) to include the libraries. This helped pass the compilation phase, but wound up crashing at Runtime because it was not able to resolve the class in the header. I replaced my static library with a framework, and this seems to work, however, this isn't ideal for me, but will have to do in the interim. I'd much rather the static library worked. I may have to revisit this another time, but I wanted to thank you for your help!

**Comment by ivanbuhov** [comment]
@vijaysharm 
> ...because it was not able to resolve the class in the header...

Can you be more specific on this? Do you receive an error? You can instruct the metadata generator to [generate yaml files or TS declarations](http://docs.nativescript.org/runtimes/ios/how-to/Use-Native-Libraries#troubleshooting) in order to verify that metadata is generated for the class in question. Therefore, we will know if the problem is in the metadata generator.

**Comment by amirofy2002** [comment]
is there any sample for this work?
