### ISSUE TITLE
iOS Dylib support

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/ios-runtime#156]
Is their documentation or any method to easily use .dylib files in ios projects?

**Comment by fealebenpae** [comment]
Using dylibs is easy. You need to open your app's Xcode project in platforms/ios and add the dylib to the Link and Embed phases as you would a Cocoa framework. In order for NativeScript to be able to discover the APIs in the library, you need to place a [module.modulemap](http://clang.llvm.org/docs/Modules.html#module-maps) file alongside the library's headers with the following content:
```
module MyLibrary {
    umbrella "MyLibrary.h"
    explicit module * {
        export *
    }
}
```
and make sure the Xcode project's Header Search Paths build setting contains the path to the folder that contains the headers.

**Comment by NathanaelA** [comment]
Awesome, this gave me the basic info I needed to figure it out.   My sqlite wrapper is now at least loading on IOS now.

 My module map doesn't use umbrella; or explicit -- My module.map file also had to reside in the ~/projectname/platform/ios folder so that it was in the clang processing path for the project.   

We might want to think of easier way to have multiple module.map files and/or some common way to build the module.map file from installed node_modules.    Or have clang check the platform/ios/.../app/\* folders that it generates from your app folder for any module.map files in the sub-folders.

**Comment by fealebenpae** [comment]
We support multiple module map files, but they have to be in separate folders. Clang looks for module maps in the include directories, or Header Search Paths as Xcode calls them. You can edit the Header Search Paths build setting in the Xcode project to add other folders that contain module maps.

The way Swift projects interface with Objective-C and C libraries is very similar to the way NativeScript does - they have the Module Search Paths build setting, which is akin to Header Search Paths. During build, the Swift toolchain looks for module maps and frameworks with embedded module maps in the directories specified by Module Search Paths. The rule of thumb is that if Swift can find a module, so can NativeScript.

The idea behind the nascent plugin support in NativeScript is that plugin authors will be able to describe transformations on the Xcode project, so that things like compiler and linker flags can be set. This means that you'll be able to use the new plugin infrastructure to instruct Xcode to look for headers and module maps in more places without having to edit the project file by hand.

**Comment by NathanaelA** [comment]
Well, then I'm totally looking forward to the plugin support; because I know documenting how to use the sqlite on IOS is going to be a pain point for any of the users using my module.   On android it is totally seamless.     Again thanks for you help; I'm not a IOS developer so digging into this is painful from someone new at it...

**Comment by PanayotCankov** [comment]
As part of the plugins mechanism dependencies to dylib that come from the SDK should be representable in the npm packages. Either as entry in the package.json or xcconfig files that would be part of the package. This is somewhat related to #62, however #62 is mostly about 3rd party libraries and framework while this one is more about describing dependencies to SDK libraries.
