### ISSUE TITLE
SystemJS

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#165]
SystemJS

More information:
 - [https://github.com/systemjs/systemjs](https://github.com/systemjs/systemjs)

Possible benefits:
 - CommonJS support (read backward compatible)
 - ES6 support
 - AMD support
 - Performance gain (see #139, https://github.com/NativeScript/nativescript-cli/issues/489)

 - [ ] Complete a POC integration with the NativeScript for iOS
 - [ ] Create two examples with the current implementation and the SystemJS to show the performance gain
 - [ ] Present the research findings, pros and cons, and escalate for all NativeScript runtimes
 - [ ] Help in the integration in the android runtime
 - [ ] Allow native modules to be consumed as JavaScript modules (see #95)

**Comment by fealebenpae** [comment]
JavaScriptCore [has already started work](https://bugs.webkit.org/show_bug.cgi?id=147876) on a ES6 modules implementation based on [the latest greatest Loader spec](https://whatwg.github.io/loader/). In light of that, we'll wait for modules to land in JavaScriptCore and implement the SystemJS loader hooks for CommonJS and AMD support on top of that, instead of relying on the [es6-module-loader](https://github.com/ModuleLoader/es6-module-loader) polyfill.

**Comment by ivanbuhov** [comment]
We will use the buit in ES6 modules in JSC. Related issue: https://github.com/NativeScript/ios-runtime/issues/291
