### ISSUE TITLE
Documentation: Extend the Debugging article with many more details

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/ios-runtime#226]
- [ ] document how safari inspector works
 - [ ] document the common debugging cases:
 - [ ] - set/remove breakpoint
 - [ ] - step, step into, step out, continue
 - [ ] - how to break on unhandled exception
 - [ ] - inspect local variables

As this is a core functionality please make it as detailed as possible so that even non experienced developers to be able to debug an app - use screenshots for most of the things. We can run it by @ikoevska as well.

**Comment by fealebenpae** [comment]
We've decided it will be best to link to [Apple's Safari Web Inspector Guide](https://developer.apple.com/library/safari/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/Introduction/Introduction.html) once it's updated for the new WebKit Web Inspector for OS X 10.11's release this Fall instead of investing resources in documenting it ourselves.
