### ISSUE TITLE
NSFileManager.copyItemAtPathToPathError crashes after copying the file...

### ISSUE THREAD

**Issue by Nathanaela** [NativeScript/ios-runtime#238]
I currently haven't setup a station to compile the IOS runtimes; so I can't try the master branch yet; but this issue does effect version 1.01 (earliest I had) to 1.12 exactly the same way.    It copies the file and crashes.   The Command line just says "Session Ended without errors", the actual logs show 

com.apple.CoreSimulator.SimDevice.F11B2A14-9647-4D61-95AE-516456A95CF1.launchd_sim[27211] (UIKitApplication:org.nativescript.Hello[0xcc16][27262]): Service exited due to signal: Bus error: 10
SpringBoard[27224]: Application 'UIKitApplication:org.nativescript.Hello[0xcc16]' crashed.

The actual code I am using is:
```javascript
var fileManager = NSFileManager.defaultManager();
var destPath = fs.knownFolders.documents().path + '/Test.sqlite';
var srcPath = fs.knownFolders.currentApp().path + '/Test.sqlite';
return fileManager.copyItemAtPathToPathError(srcPath, destPath, null);
```

Please note it doesn't matter if I create a interop variable for the Error.      Also note; it only crashes if it copies the file; if the file is already present (so it would then fail to copy) then it actually returns "false" and the program continues fine.

**Comment by jasssonpet** [comment]
I have managed to reproduce the issue with the following snippet and will take a look at it:
```javascript
var fs = require('file-system');

var file = fs.knownFolders.currentApp().getFile('Test.sqlite');
console.log(file.path);

var srcPath = fs.path.join(fs.knownFolders.currentApp().path, 'Test.sqlite');
console.log(srcPath);

var destPath = fs.path.join(fs.knownFolders.documents().path, 'Test.sqlite');
console.log(destPath);

var fileManager = NSFileManager.defaultManager();
var errorRef = new interop.Reference();
if (!fileManager.copyItemAtPathToPathError(srcPath, destPath, errorRef)) {
    console.error(errorRef.value);
    return;
}

console.log('Successfully copied file');
```

**Comment by ivanbuhov** [comment]
This issue is caused by a bug in our metadata generator. We were trying to guess (with the help of some heuristics - read more [here](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmRules.html)) which method from the iOS SDK returns retained object and save this information in metadata. Our guessing was not quite right in some rare cases. This is the case with `copyItemAtPath:toPath:error:` method. We assume that the method returns retained object because its selector starts with `copy`. As part of another feature for v1.2 we changed the way of checking which method returns retained object (now we ask Clang to tell us), so in v1.2 the issue is fixed. Here is the commit that fixes it https://github.com/NativeScript/ios-metadata-generator/commit/aedeaf7ca021bb9d8aa526d5f3a766e3755a4575.

**Comment by NathanaelA** [comment]
Awesome.  I started getting eveything on my mac to build the latest.  But it is good to know that it is fixed in the next version.

**Comment by srnaik** [comment]
where knownFolders.documents() is supposed to be located and it doesn’t tell me in the documentation.  What path is that? Where are these files? Please let me know

**Comment by ivanbuhov** [comment]
@srnaik [here is the definition of documents()](https://github.com/NativeScript/NativeScript/blob/74800924f83b1eb45e37e983fd1be481dec8a5c0/tns-core-modules/file-system/file-system.ts#L470-L479). On iOS it returns [NSFileManager.defaultManager().URLsForDirectoryInDomains(NSSearchPathDirectory.DocumentDirectory, NSSearchPathDomainMask.UserDomainMask)](https://github.com/NativeScript/NativeScript/blob/74800924f83b1eb45e37e983fd1be481dec8a5c0/tns-core-modules/file-system/file-system-access.ios.ts#L246-L248).
And here is the [Android implementation](https://github.com/NativeScript/NativeScript/blob/74800924f83b1eb45e37e983fd1be481dec8a5c0/tns-core-modules/file-system/file-system-access.android.ts#L181-L184).

**Comment by srnaik** [comment]
Thank you @ivanbuhov , that was very helpful !
