### ISSUE TITLE
Running app on device untethered = unresponsive phone

### ISSUE THREAD

**Issue by manijak** [NativeScript/ios-runtime#246]
Hi,
Posted this first in google-groups, was asked to post the issue here instead.
I am able to deploy my app to my device and run it, but only while it is connected to the dev machine.

If I run the app while disconnected from the machine, the entire phone goes bananas. I can't do anything. Can't answer the phone, can't text, can't even lock\unlock it, no response...

I have to re-connect it to the dev machine and re-deploy the app. Only then I get back the controll of my phone.

This is really bad if you (or someone else) starts the app by accident when away from the dev-machine. Phone becomes useless. :)

Is there another way to deploy apps to phone, and run them untethered and without issues?

Noticed one other thing:
When I use "tns deploy ios" it keeps the terminal running with debug info from the device. Even if I close the app. Can't seem to exit the debug mode at all. Have to force-exit terminal. 

- Tested on {N} versions: 1.1.2 & 1.2.0
- Dev machine:  MacMini - mid 2011 with latest Yosemite and latest Xcode
- iPhone 6 with iOS 8.4 (12H143)

**Comment by fealebenpae** [comment]
Hi,
Can you please [get the output from the device console](http://stackoverflow.com/questions/24484817/how-to-get-device-console-in-xcode6) after you run the app untethered and then reconnect to your dev machine and copy it in a gist or pastebin somewhere so we can take a look?

**Comment by manijak** [comment]
Ok, I noticed a few thing here. 

- If I deploy the app, run it, disconnect USB (while the app is running). I can close and open the app normally, no issues. 

- If I deploy the app, run it, close the app, disconnect USB. Restart app and the phone hangs. 
- If I deploy the app, run it, close the app, force close Terminal & disconnect USB. Restart the app and the phone hangs. 

Log: http://pastebin.com/xDjnxeqQ
App restarted at 15:10

**Comment by fealebenpae** [comment]
By "close the app" do you mean exiting to the home screen by pressing the home button once, or force closing it from the multitasking menu?

**Comment by fealebenpae** [comment]
Also, do you use the `tns deploy` command to launch the app, or do you launch it manually by tapping its icon on the home screen?

**Comment by manijak** [comment]
Yes, with "Close the app" I mean force close from the multitasking menu.

I used "tns deploy ios", the apps gets deployed and starts automatic.

**Comment by fealebenpae** [comment]
I managed to reproduce something similar on my iPhone 5s running iOS 8.4 and Xcode 6.4 - I run the app using `tns deploy` or `tns device run`, force close it, disconnect the USB cable and then I try to start the app from the home screen. I tap its icon, but nothing happens, and eventually my phone restarts.

Following the above steps I did the following: I created a new Xcode project from the Single View template and ran it on my phone, then I force closed the app, disconnected the cable and tried to run the app again. I got the exact same behavior.

The NativeScript CLI uses the Xcode debugger to launch an app on a connected device and, seeing as how I observed the same problem in Xcode, this leads me to believe that we're hitting an issue within the Xcode debugger itself. Unfortunately there is little we can do to rectify this as we simply piggy-back on top of Xcode. As a possible workaround I can suggest to restart the phone by holding down the power and home buttons simultaneously for several seconds when it becomes unresponsive. Alternatively, you can try the `tns run ios --justlaunch` command which will detach the Xcode debugger immediately after starting the app instead of keeping it alive to pipe debug information to the terminal.

**Comment by manijak** [comment]
Ah I see. Never tried to do it via xcode myself. Glad to hear that it's not a cli issue. At least there is a safe method to deploy the app to the device, and that is disconnecting the USB while the app is running. 

Thanks for the --justlaunch command, didn't know about that. Will try. 

And thanks for your time & help.
