### ISSUE TITLE
OSX & xCode Version requirements question

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/ios-runtime#303]
The main readme for this repo states that we need OSX 10.10.3+ and XCode 6.3+ -- can someone point to me why we need that late of an OS and XCode 6.3?  

I'm currently have a Maverick build server with XCode 6.2 all fully functional and rather than spend a lot of time upgrading to 10.10.3 if I don't need to; can someone point to me why 10.10.3/6.3 is the minimum and if their is maybe a easy way to work around the minimum if this truly is the case?

**Comment by fealebenpae** [comment]
These are the prerequisites necessary to build JavaScriptCore. We use Yosemite in the team, and 10.10.3 is the minimum supported Yosemite because of a few system headers for frameworks such as PDFKit which were added in that version.

You might be able to build on Mavericks with Xcode 6.2 (the WebKit docs say Xcode 6.1.1 is the minimum if you want to target iOS), but this isn't something we've tested ourselves.

**Comment by NathanaelA** [comment]
Awesome, so it might be possible without spending too much more time on it.   I just need to get a Apple signing key for the project and try it out...    Thanks @fealebenpae for the info.   I'll let you know what I find out once I can purchase a signing key for my build server...

**Comment by fealebenpae** [comment]
With Xcode 7, [you can deploy on your devices without paying the $100 yearly fee](https://developer.apple.com/library/prerelease/ios/documentation/DeveloperTools/Conceptual/WhatsNewXcode/Articles/xcode_7_0.html#//apple_ref/doc/uid/TP40015242-DontLinkElementID_4).

**Comment by NathanaelA** [comment]
I didn't now that; but that wouldn't serve the purpose anyways.I need to be able to distribute them -- its for building the ios nightlys on the nativescript.rocks site...

**Comment by fealebenpae** [comment]
You don't need to codesign the runtime in order to distribute it - static libraries aren't codesigned and frameworks are re-signed by the NativeScript template application during build so their original signing identity doesn't matter.  In fact, to speed up the build you can edit the build script and remove the two test apps which are only used for CI testing and aren't part of the final distributable.

**Comment by NathanaelA** [comment]
I knew that it would be re-signed; but everything I was reading said that it would still be signed by your key during building (and the error was about missing the signing key).     If the test app is what is causing it to fail; I'll try to remove it and see if that helps.   Thanks for the pointer.

**Comment by fealebenpae** [comment]
For the framework build you can use [these instructions](http://stackoverflow.com/questions/11034133/building-ios-applications-using-xcodebuild-without-codesign) to disable codesigning completely, then after you've disabled the test apps from being built you won't need a key to build a distributable package.

**Comment by NathanaelA** [comment]
@fealebenpae - Thanks, that insight actually worked very well.

**Comment by NathanaelA** [comment]
Oh and I should say, you can build this perfectly fine on Maverick with xCode 6.2...

**Comment by fealebenpae** [comment]
Thanks, good to know.
