### ISSUE TITLE
building a tvOS app

### ISSUE THREAD

**Issue by enchev** [NativeScript/ios-runtime#365]
_From @mrjeremy28 on October 11, 2015 3:23_

I'm pretty new to NativeScript, but noticed the power it has to deploy to multiple platforms using a single code base. I've used JavaScript before and am looking in creating a quiz like app that uses mobile devices as controllers.
I'll be using a nodejs backend for all of the APIs, but trying to get the main TV app up and running and am looking for any guidance.

_Copied from original issue: NativeScript/NativeScript#917_

**Comment by enchev** [comment]
_From @fealebenpae on October 11, 2015 17:20_

Hi @mrjeremy28 

Right now we don't support tvOS like we do iOS and Android, but there is a sample project with the NativeScript runtime for tvOS [here](https://github.com/nativescript/sample-tvos) that you can play with.

**Comment by mwcampbell** [comment]
I'm looking at using NativeScript for an upcoming project, and I want to target tvOS as well as iOS and Android.

I notice a couple of issues with the sample-tvOS "proof of concept" project:

* The NativeScript runtime included in the repo is only compiled for x86_64 (i.e. the simulator). Have you verified that the runtime can actually run on an Apple TV?

* Xcode and the iTunes Store require bitcode to be enabled for actual device builds. Will this pose a problem for libffi, which includes ARM64 assembler for the closure trampolines?

* The tvOS sample doesn't include the cross-platform UI modules at all. If I replace that module with the sampleGroceries app, I get the login screen, but the style looks all wrong on the TV simulator (a 12-point font is way too small), and activating the buttons does nothing. I think it will be necessary to treat tvOS as a distinct platform from iOS.

**Comment by fealebenpae** [comment]
Hi @mwcampbell,

We don't have access to the new Apple TV hardware, so we can't verify that the runtime runs on it. It does compile for its ARM variant and I am confident it will run on the actual hardware.

The bitcode requirements match those for iOS in that it allows assembly code. We don't ship the runtime with bitcode right now because it balloons the size of the `tns-ios` package in npm, and bitcode is still optional on iOS, but you can build the runtime and libffi on your own with the `-fembed-bitcode` compiler flag.

Even though tvOS uses UIKit it mandates new design patterns and interface guidelines and we are aware of that. Should interest in tvOS build to such a level that we decide to support it, it will be as a distinct platform alongside iOS and Android.

Our metadata generator doesn't recognize tvOS as a Darwin platform because the open-source version of the Clang compiler we use underneath doesn't. We had to feed the tvOS SDK to the metadata generator while making it believe it was dealing with iOS, and that's why availability attributes that would have hidden an API on tvOS didn't kick in. This is a minor issue, though, as the API would do no harm just being in the metadata as long as it isn't called. Right now tvOS isn't high enough on our list of priorities to fix this, but we'd welcome contributions from the community.

**Comment by BigLep** [comment]
I know this has been closed for ~3 years.  Has there been any more discussion on providing first class support for tvOS?

**Comment by etabakov** [comment]
Hey, @BigLep. Providing first class support for tvOS is currently not in our immediate plans. You can check out our [roadmap](https://www.nativescript.org/roadmap-and-releases) for more details on what we are planning to work on. Also, now is your time to influence the NativeScript vision by filling out the [NativeScript Community Survey](https://progress.co1.qualtrics.com/jfe/form/SV_eJOutHRaMH4klcV), if you haven't done it already.
