### ISSUE TITLE
NativeScript Inspector.app is compiled to only support later versions of OSX

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/ios-runtime#387]
The NativeScript Inspector.app needs to be run able on all versions of Mac OS-X supported.  Right now on 10.9.x this fails to run with the error code -10825, which according to apple says incompatible version...   So you can't run iOS debug on a fully upgraded OSX 10.9 box...

**Comment by NathanaelA** [comment]
The info.plist states 10.10 is the minimum.   Is their an actual requirement for 10.10, or can this be dropped to 10.9?

**Comment by KristinaKoeva** [comment]
In order to support 10.9 OS X we have to distribute webkit frameworks build for 10.9 OS X with our debugging application. This would greatly increase the app size, so we've decided to support only the current released OS X and the previous one.

**Comment by NathanaelA** [comment]
Sorry, you are confusing me.  Maybe I'm not understanding you.  I can build everything fine on OSX 10.9...  

The only thing I can't do is run the debug system.  Why would making the NativeScript Inspector app have a minimum version of 10.9 cause you to have to distribute anything else?   And what else would you have to distribute exactly to make 10.9 work for debugging?

**Comment by KristinaKoeva** [comment]
To show the content of the NativeScript debugging application we use a [WebView class](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/WebKit/Classes/WebView_Class/) that comes from the webkit framework. The content of the debugging application uses features that are not yet included in the official build of webkit so this forces us to bundle our debugging application with a custom webkit build. Webkit needs to be build differently for every OS X, so in order to support 10.9 OS X we would have to embed yet another webkit framework that is build for 10.9 OS X. 
The approach is similar to the way [Webkit Nightly](http://nightly.webkit.org/) distribute itself. If you examine the Webkit Nightly application you could see that there are frameworks for all supported OS X  (under ```Contents/Frameworks```)

**Comment by NathanaelA** [comment]
Ouch. I see.

Can someone who is familiar with this process walk me through the steps to change and build my own 10.9 debug version.  I already build the nativescript-ios runtimes every night on nativescript.rocks; so I have no issues making another build; but I'm not that familiar with osx runtime changes that would need to be changed to make this work...

**Comment by KristinaKoeva** [comment]
To build webkit you should execute [build-webkit](https://github.com/NativeScript/webkit/blob/7d6cc785394120ad1ae578e7cad3ae166a1812a2/Tools/Scripts/build-webkit) script in release configuration ```build-webkit --release```. More information could be found at http://www.webkit.org/building/build.html
Once the build is finished you should take the following frameworks
```
JavaScriptCore.framework
WebCore.framework
WebInspectorUI.framework
WebKit.framework
WebKit2.framework
WebKitLegacy.framework
```
and place them under ```[ios-runtime-location]/src/debugging/inspector/Inspector/Frameworks``` folder. The inspector application references those frameworks into the Embed Frameworks build phase. You should then open the ```[ios-runtime-location]/src/debugging/inspector/Inspector/Inspector.xcodeproj``` and build the Inspector target. The build shoud produce two applications located into the project Derived Data. Take the Inspector.app, change its name to NativeScript Inspector.app and replace the original NativeScript Inspector.app with it. 
If everything is successful nativescript-cli should take you custom build application and use it instead of the official one.
