### ISSUE TITLE
HomeKit

### ISSUE THREAD

**Issue by rclai** [NativeScript/ios-runtime#409]
Hi, I just wanted to know whether it is possible to use HomeKit right out of the box with Nativescript? I know the homekit.h library is available from the header file, but I just wanted to make sure there isn't something special that needs to be done to be able to use it.

**Comment by ivanbuhov** [comment]
Hi @rclai, 
To use `HomeKit` in your app, first, you have to [enable it](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/HomeKitDeveloperGuide/EnablingHomeKit/EnablingHomeKit.html#//apple_ref/doc/uid/TP40015050-CH2-SW2) which includes editing the Xcode project manually, so you have to open `platforms/ios/YourApp.xcodeproj` and follow [these steps](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/HomeKitDeveloperGuide/EnablingHomeKit/EnablingHomeKit.html#//apple_ref/doc/uid/TP40015050-CH2-SW2). Bare in mind that this is valid if you are making native app, too.
Now you are able to use all the functionality of `HomeKit` in your `NativeScript` app. I made a [proof of concept app](https://gist.github.com/ivanbuhov/d7ad9a29d29afd01c8da) which is using a minimal part of `HomeKit` (`HMHomeManager` and `HMHomeManagerDelegate` APIs) in order to validate the scenario.

**Comment by rclai** [comment]
Thanks.
