### ISSUE TITLE
Research debugger integration with Visual Studio Code

### ISSUE THREAD

**Issue by atanasovg** [NativeScript/ios-runtime#415]
Now that Visual Studio Code [supports extensions](https://code.visualstudio.com/updates), let's see whether it is technically possible to integrate our debugger machinery with it.

**Comment by KristinaKoeva** [comment]
I used [vscode-chrome-debug](https://github.com/Microsoft/vscode-chrome-debug) as a base for the research. They've provided a nice wrapper around the debugger protocol that we could use . With few modifications I was able to plug our communication channel and on my machine :smile_cat:  I can
1. Set/Remove breakpoint
2. Hit breakpoint
3. Step in, over, continue
4. Show call stack and variables
5. Create a watch expression 
6. Log messages from console.log to VS Code console

 I plan to research how hard would be to add a new window/pane to VS Code so that we could eventually show our DOM tree.

**Comment by fealebenpae** [comment]
@KristinaKoeva could you please fork [vscode-chrome-debug](https://github.com/Microsoft/vscode-chrome-debug) and apply your changes on top?

**Comment by ivanbuhov** [comment]
The first beta is coming soon (https://github.com/NativeScript/nativescript-vscode-extension).

**Comment by lelong37** [comment]
+10, awesomeness can't wait.. already using VSCode for NS development with TS...
