### ISSUE TITLE
Strange behavior of the JavaScriptCore engine

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/ios-runtime#416]
After the recent WebKit update (https://github.com/NativeScript/ios-runtime/pull/362) some very strange things happen:

* Failing unit tests, only when the Web Inspector is attached
* Crash when using `JSON.parse()`
* The JavaScriptCore JIT is behaving in some really bizarre ways
* Failing integration tests

Let's try out with a newer version of JavaScriptCore and hope that all of this is fixed there.

**Comment by fealebenpae** [comment]
Does this happen on a simulator, on a device as well? If simulator, I'd finger the JIT as the culprit, especially given the ongoing development of the new B3 system in JavaScriptCore. It'd be better to just disable the JIT rather than shoot in the dark with newer JavaScriptCore versions, if of course my suspicions are correct.

**Comment by jasssonpet** [comment]
This behavior was observed on simulator also with the JIT disabled.

**Comment by fealebenpae** [comment]
Have you tried granularly disabling the JIT - turning off DFG while leaving Baseline on?

**Comment by ivanbuhov** [comment]
Since we have [almost ready for merge](https://github.com/NativeScript/ios-runtime/pull/422) update of JSC in which some of the strage behaviours disappeared, I suggest testing all buggy scenarios with it and if something goes wrong we can investigate it.

**Comment by fealebenpae** [comment]
We've agreed that running the unit tests with an inspector attached is not something we'd like to invest in supporting right now. The JIT has been disabled, so that shouldn't give us any more trouble.

Now that #422 has landed I'll close this, with the possibility of reopening should the integration tests fail again.
