### ISSUE TITLE
Call global onUncaughtError callback when a NSException occurs

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/ios-runtime#434]
```javascript
var arr = NSArray.array();
var obj = arr[3]; // A NSException is raised

global.__onUncaughtError = function (e) {
    // This should be called
}
```

**Comment by fealebenpae** [comment]
I'm against this, as that would require the runtime to handle all Objective-C exceptions globally, and the runtime has no business doing that.

Interested parties should ship a plugin with a framework that uses `NSSetUncaughtExceptionHandler` to achieve the same effect.

**Comment by darind** [comment]
If this is so, then in my opinion both runtimes should be consistent. Currently the Android runtime invokes the global exception handler for native exceptions.

**Comment by jasssonpet** [comment]
> as that would require the runtime to handle all Objective-C exceptions globally, and the runtime has no business doing that

What if the Objective-C exception was triggered by some JavaScript code. We could provide some additional information about that.

**Comment by fealebenpae** [comment]
The Android runtime translates Java exceptions to JavaScript errors so they can be caught in regular JavaScript, whereas the iOS runtime does not.

**Comment by darind** [comment]
The Android runtime passes the native Java exception (the Throwable object) to the args.android.nativeException in the global error handler.

**Comment by fealebenpae** [comment]
@darind The iOS runtime does not deal with Objective-C exceptions at all, and I'm not about to change that only for the sake of `global.__onUncaughtError`. Objective-C exceptions should be handled using `NSSetUncaughtExceptionHandler` in native, rather than in JavaScript.

**Comment by fealebenpae** [comment]
@jasssonpet We can think of a way to use `+[TNSRuntime _getCurrentStack]` in a crash reporter. That way a crash reporter could record the state of JavaScript execution when an unhandled Objective-C or C++ exception is thrown, or even when a signal is raised.

**Comment by atanasovg** [comment]
I agree that hooking each and every ObjC Runtime exception globally is not appropriate. However, my opinion is that everything we pass **through the bridge** should be exception-aware one way or another. Can't we do `try/catch` for bridge calls? This way we will catch the `NSException` in the above snippet without hooking all the exceptions globally. @Plamen5kov has already done this for the Android Runtime and the performance measurements show no significant hit.

**Comment by jasssonpet** [comment]
I'm interested in measuring the impact of Objective-C `try`/`catch` on marshalling with our performance tests :smile_cat:

**Comment by atanasovg** [comment]
@jasssonpet :+1:

**Comment by fealebenpae** [comment]
@atanasovg: Exceptions in Objective-C are not meant to be general-purpose control flow tools. They are used to indicate programmer errors such as missing methods or invalid arguments and as such do not represent recoverable conditions. You'll notice that Swift does not support Objective-C exceptions at all, and very few libraries out there actually raise exceptions and virtually no library catches exceptions. As such they are nothing like Java exceptions. @darind wants to implement a global exception handler via `__onUncaughtError`, whereas it would be far better to use the existing global exception handler mechanism in Objective-C. It is beyond overkill for the bridge to `@try/@catch` every single call to native just because a seldom-used crash reporter doesn't want to call an extra function. Should the bridge monitor POSIX signals as well to save someone the trouble of calling `sigaction` directly?

**Comment by jasssonpet** [comment]
> Should the bridge monitor POSIX signals as well to save someone the trouble of calling sigaction directly?

That's actually not a bad suggestion.

I've seen far more signal errors than Objective-C exceptions. At the moment the {N} modules team are calling the private `[TNSRuntime __printCurrentStack]` on each crash. IMO, if we could automatically provide users with the JavaScript stack trace, that would ease the development process.

**Comment by atanasovg** [comment]
What we should always keep in mind is that the primary development language we promote is JavaScript and exceptions are perfectly valid way to handle erroneous state/input. Forcing JS devs to dig into the internals of ours or the ObjC Runtime is something we do not want to do. Moreover, what @darind says about feature parity and consistency is perfectly valid. Ideally we would have similar behavior wherever possible.

>It is beyond overkill for the bridge to @try/@catch every single call to native

Let's verify this statement - if it is really an overkill then obviously we will not want to degrade the performance for the sake of the global exception handler.

**Comment by jasssonpet** [comment]
@fealebenpae Here are the results after [adding `try`/`catch` in each call](https://github.com/NativeScript/ios-runtime/blob/jasssonpet/nsexception/src/NativeScript/Calling/FFICall.mm#L98-L103) on top of our current master branch:

## 32-bit (iPhone 5)

| Test       | Master            | Exceptions        |
| ---------- | ----------------- | ----------------- |
| Primitives | 2552ms - 2666ms   | 2928ms - 2944ms   |
| Strings    | 801ms - 805ms     | 796ms - 812ms     |
| Big data   | 13138ms - 13196ms | 13054ms - 13204ms |

## 64-bit (iPhone 5s)
| Test       | Master          | Exceptions      |
| ---------- | --------------- | --------------- |
| Primitives | 988ms - 998ms   | 1038ms - 1047ms |
| Strings    | 481ms - 489ms   | 469ms - 477ms   |
| Big data   | 1200ms - 1206ms | 1192ms - 1204ms |

There seem to be no significant differences, except for the Primitives test (calling a method one million times) on 32-bit platforms.

**Comment by fealebenpae** [comment]
The "Strings" and "Big data" benchmarks carry intrinsic copying/locking overhead of their own and that's why exception handling has a negligible impact. But the vast majority of our ffi calls marshal only primitives like pointers and such and they take a sizable hit on 32bit devices, which are slow enough already.

I maintain my stance that exception handling would bring no benefit and only introduce additional overhead in our already weakest performance target, especially given that @darind's scenario is best implemented using `NSSetUncaughtExceptionHandler` in any case.

**Comment by atanasovg** [comment]
A summary:

- The modules already provide that [onUncaughtError](https://github.com/NativeScript/NativeScript/blob/master/application/application.d.ts#L140) callback and it should available and behave the same way in both Android and iOS worlds.
- There is no significant (at least proven) overhead on try-catching NSErrors

So, to me it seems this more a philosophical discussion: should we try-catch NSErrors or not. My thinking is that the Runtime, as a library, should be defensive and handle erroneous user input correctly (I am not suggesting try/catch is the only viable way to do this) - the snippet provided by @jasssonpet is exactly such erroneous case. Additionally, in such cases the modules API should work and call its `onUncaughtError` method.

I see three possible solutions here:

1. The Runtime uses `try/catch` and calls `global.__onUncaughtError` upon `NSError`s
1. The Runtime installs the `NSSetUncaughtExceptionHandler` and calls `global.__onUncaughtError`. This requires that we may recognize `NSError`s that are related to utilizing the Runtime itself.
1. The modules install the `NSSetUncaughtExceptionHandler` and utilize their callback. This brings implicit knowledge as to what the Runtime handles and what not - in some cases the `global.__onUncaughtError` is called and in some - not.

I personally think it is the Runtime that should handle such situations - one way or another.

**Comment by fealebenpae** [comment]
I think you are conflating `NSError` and `NSException`. The runtime already handles `NSError` by wrapping it in a JavaScript value and throwing it like a regular Error. `__onUncaughtError` will be invoked with an `NSError`.

`NSException`, on the other hand, often represents an irrecoverable condition and thus is not exposed to JavaScript. The sole concession the runtime makes for `NSException` is to set a global uncaught exception handler when an Inspector is attached so as to forward the exception to the Inspector. In all other cases the runtime does not set an uncaught exception handler as its presence messes up the exception's stack trace.

If I may refute @atanasovg's solutions:
1. `@try/@catch` introduces an overhead on 32bit devices, and `NSException`s are not meant to participate in control flow.
2. Setting a global exception handler indiscriminately will obfuscate the stack trace of the exception so that debugging and Apple's built-in crash reporting will include NativeScript frames in crashes where there were none in the first place.
3. Same as above.

Established crash reporters such as PLCrashReporter and KSCrash only install exception and signal handlers after they have been explicitly instructed to do so, not by virtue of their mere presence. That's why I think it would be best for the analytics plugin to manually call `NSSetUncaughtExceptionHandler` after it has been enabled, instead of relying on `__onUncaughtError` to relay exceptions. Analytics would have to call `sigaction` as well in order to install signal handlers, and that's another thing not covered by `__onUncaughtError`.

In essence, I see two problems - first, exposing `NSException` to JavaScript is both nonsensical in that it would not enable developers to do more AND comes at a cost on 32bit devices, and Swift does not do so either. The other problem is that installing exception and signal handlers in all cases would degrade the debugging and crash reporting experience in applications that do not use Telerik's analytics plugin.

I think piping Objective-C exceptions through `__onUncaughtError` in JavaScript is a bad decision for the reasons I've detailed above, but seeing as how you're set on doing it that way, I most regretfully wash my hands of this. Besides, @jasssonpet seems keen to implement this.

Be sure to add a signal handler and a C++ exception handler, @jasssonpet.

**Comment by jasssonpet** [comment]
btw, I've finally found the StackOverflow answer (from an Apple employee) that we spoke of:

> Any exception that passes through system framework code will leave said framework in an undefined state.. Catching said exceptions and trying to recover from it will lead to memory leaks, undefined behaviour and crashing.

> Just because the language has syntax to support something, doesn't mean the frameworks are designed to support that thing, too. The frameworks have a very firm policy: exceptions are unrecoverable errors. Trying to catch and recover goes against framework design and, quite clearly, an exception that "jumps over" framework based stack frames is a violation of documented policy and will yield unspecified behavior.

http://stackoverflow.com/a/3379240/477981

**Comment by atanasovg** [comment]
@jasssonpet Thanks for digging this out. Still, the question is why the NSException object is catchable at first place and why it isn't - like in Swift. I am still not understanding why the concrete exception we are talking about - index out of range - would break the whole ObjC runtime but I guess Apple simply didn't take the time to bother which exceptions are really not recoverable and which are.

@fealebenpae Thanks for the explanation - it makes more sense now. Nothing is yet decided. I am just trying to figure out myself would it be any harm to enable this scenario through the ways I suggested. I for one find this discussion really helpful to me and hopefully to other people as well. Btw, I am still not sure that the `try/catch` overhead is significant. According to @jasssonpet results it is not. Do you have some other measurements that prove the opposite? And how do you envision we should proceed from the modules API perspective? Probably document it well when it will work and when not?

**Comment by fealebenpae** [comment]
@atanasovg: @jasssonpet's numbers show that exception handling slows down the `ffi_call` fast-path on 32bit devices by roughly fifteen percent. That fast-path is widely used by calls which do not make allocations while marshaling arguments.

I think what you're asking is more of a philosophical question - should `__onUncaughtError` handle every imaginable error on iOS. That includes POSIX signals raised by things like dereferencing null pointers, exceptions in C++ code called by Objective-C code, and Objective-C exceptions. There are debugging facilities in place that handle these conditions better than we ever could. What would be accomplished by calling `__onUncaughtError` on `SIGSEGV`? For that matter, does the Android runtime call `__onUncaughtError` when there's a segmentation fault? I think the error handler should only concern itself with things that are thrown in JavaScript - actual JavaScript errors, and things we present as errors, such as exceptions on Android and `NSError` on iOS.

I think `__onUncaughtError` is tainted by historical bad design choices like `window.onerror`, but that is neither here, nor there. In fact, I think it was @PanayotCankov or @jasssonpet who suggested we come up with a `NSSetUncaughtExceptionHandler` equivalent for the runtime, and that's how `TNSSetUncaughtErrorHandler` was born, which makes more sense to me as a global error handler because it lives outside the JavaScript world.

**Comment by atanasovg** [comment]
Let's not over-complicate the original issue with segmentation faults, which are not caught by a simple `try/catch` block anyways (and yes, the Android Runtime does not handle these as well). Given [framework's means](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/Exceptions/Tasks/HandlingExceptions.html) of handling exceptions my thinking is that it is viable to pass all bridge calls through a `@try/@catch` block. 

Now comes the performance side. The results show that 1 000 000 calls bring ~300ms overhead on 32-bit devices. Is this significant - we need to see how many calls on average an application makes - during loading and interaction. I doubt that these will be user-perceivable by any means (except for example by a heavy algorithm that calls extensively to Objective C). Still, although synthetic, 15% is a 15% degrade and this is a good enough reason not to push a `try/catch` implementation.
