### ISSUE TITLE
Remove all declarations that start with underscore

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/ios-runtime#44]
There are [many private ugly APIs](https://gist.github.com/anonymous/91c80405c05488841b51) that only clutter the debugger and global object. We should remove them from the metadata.

The JSC C API hides them too.

**Comment by ivanbuhov** [comment]
For now, we are not going to remove the APIs, starting with underscore. Aftrer introducing Module Proxies (https://github.com/NativeScript/ios-runtime/issues/95) the global object will not be polluted with "ugly" APIs. The issue is open-ended and if there are problems with these APIs in the future we can reconsider it.
