### ISSUE TITLE
TNS_TYPESCRIPT_DECLARATIONS_PATH places d.ts files in wrong directory

### ISSUE THREAD

**Issue by speigg** [NativeScript/ios-runtime#446]
Uncommenting the line in `nativescript-build.xcconfig`:
```
TNS_TYPESCRIPT_DECLARATIONS_PATH = "$(SRCROOT)/typescript-declarations"
```

Places the generated d.ts files at 
```
YOUR_APP/platforms/ios/internal/metadata-generator/bin/"/Users/username/...a..bunch..of..folders/platforms/ios/typescript-declarations"
```

rather than the expected:
```
YOUR_APP/platforms/ios/typescript-declarations
```

**Comment by fealebenpae** [comment]
That could be because of some over-zealous path escaping I added a while ago. I'll look into it and see if that's the case.

You can always define the `TNS_TYPESCRIPT_DECLARATIONS_PATH` environment variable in your shell instead of modifying the .xcconfig and that [should work](http://jasssonpet.github.io/generating-typescript-declarations-in-nativescript-for-javascript-coffeescript-code-completion/).

**Comment by speigg** [comment]
It works when I remove the quotes in the xcconfig file

**Comment by fealebenpae** [comment]
That's great to hear! Perhaps you'd like to submit a pull request that removes the quotes? :)

**Comment by speigg** [comment]
Sure. Also, where are all the type declarations for `interop.*` ? I've added the generated d.ts files to the `filesGlob` setting in my `tsconfig`, and the only thing that seems to be missing now are the `interop.*` types (the types listed here: https://docs.nativescript.org/runtimes/ios/types/Runtime-Types).

**Comment by speigg** [comment]
Okay, looks like the `interop.*` types are in tns-core-modules@1.6.0, which hasn't been released yet. I'll just have npm fetch it directly from github.

**Comment by fealebenpae** [comment]
The `interop` namespace is declared in https://github.com/NativeScript/ios-runtime/blob/master/src/ts/Interop.d.ts.

**Comment by speigg** [comment]
Ah, thanks. That's easier.
