### ISSUE TITLE
Any processMessages type functionality

### ISSUE THREAD

**Issue by N3ll** [NativeScript/ios-runtime#465]
_From @NathanaelA on January 1, 2016 2:45_

Ok, so I'm starting up my application and I'm doing a lots of file, database and raw data processing on startup and once it is all done I switch to the main screen from the startup progress screen.   However, even though I am updating the status label and progress bar; you do NOT see any of the changes because of course the main thread has been so busy doing all its work that it never actually had a chance to pass control back down to the android layer apparently to update the screen.  (I haven't tried this on iOS yet)    Since we don't have background thread ability yet; Is their any way I can force the android runtime to run and update the screen or do I have to split everything up into really small functions that I can then use setTimeout's so that their is a break between each one?  

_Copied from original issue: NativeScript/NativeScript#1315_

**Comment by N3ll** [comment]
_From @x4080 on January 1, 2016 3:35_

What if the background process using native android library?

**Comment by N3ll** [comment]
_From @NathanaelA on January 1, 2016 4:26_

Actually, I might have to go that way in the future since it is so intensive.  But for the prototype I'd rather not write Java and ObjectiveC code if I don't have too.   :-)       

So in the meantime, in all my exploring I haven't seen anything like this; but there might be a feature somewhere deep in the Runtimes that will allow me to push out of the JS VM back into the Android NDK/Java level and get the screen updated...

**Comment by N3ll** [comment]
_From @x4080 on January 1, 2016 9:25_

Yea actually i suggested that sonehow there is 2nd javascript in the background it will be very helpful

**Comment by N3ll** [comment]
_From @NathanaelA on January 2, 2016 17:21_

I'm pretty sure a feature to force the runtimes to update the screen (or actually suspend the JS runtimes and make the Android/iOS handle their message loops) is something that doesn't exist; but I figured it couldn't hurt to ask.  

@x4080 Having a background thread (which also would solve this, is bug report #85 ); as you can see  many people have commented on it.   I'm hoping that more people will +1 it so that it will become the top issue.  :grinning:

**Comment by N3ll** [comment]
_From @x4080 on January 3, 2016 11:47_

Actually i wrote the last comment there :)

**Comment by N3ll** [comment]
This issue was moved to NativeScript/android-runtime#324

**Comment by fealebenpae** [comment]
On iOS you can use the [Run loop API](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/Multithreading/RunLoopManagement/RunLoopManagement.html) to run the main thread run loop. The runtime however does not work with the run loop directly and thus you will have to handle this on your own, just like you would have to do in Objective-C in the same condition.

**Comment by x4080** [comment]
You mean for background thread? So nativescript ios support backgroud thread? No restriction?

**Comment by fealebenpae** [comment]
JavaScript in and of itself can only run on one thread at a time. However, if you have a long-running operation on the main thread you can manually run the run loop in order to process input on the device so that the app does not freeze from the point of view of the user.

**Comment by x4080** [comment]
Oh now i understand

**Comment by x4080** [comment]
Any equivalent in android?

**Comment by fealebenpae** [comment]
I'm afraid I'm not familiar enough with Android, hopefully some can help you in the Android issue: https://github.com/NativeScript/android-runtime/issues/324

**Comment by x4080** [comment]
You already help a lot :)

**Comment by NathanaelA** [comment]
@fealebenpae - Thanks I'll check that out; now I just need the equivalent on Android.

**Comment by atanasovg** [comment]
@NathanaelA We have done something similar (also known as "Modal Message Loop" on Windows) for our unit tests where we needed to block code execution of the UI thread at a certain point and continue with message processing. Still, while there are official APIs for iOS, for Android the implementation is quite hacky since there are no public APIs and we are NOT recommending using this approach. You may still use it as a reference though:

https://github.com/NativeScript/NativeScript/blob/master/apps/tests/TKUnit.ts#L286-L388

**Comment by NathanaelA** [comment]
@atanasovg -- Awesome, I was thinking I would have to use the Looper, looks like you came to the same conclusion.  And I was thinking it might end up being hacky.  Would be nice if the runtime you expose something like processMessages() as a global so that it could automatically drop out of the v8/nitro back into the runtimes process any pending messages and then re-enter the JS engine...

**Comment by NathanaelA** [comment]
Just for anyone following in my footsteps; at least on Android I have to do this:

```
var page;
exports.navigatedTo = function(args) {
   page = args.object;
   setTimeout(startProcessing, 0);
};

function startProcessing() {
  // get progressbar & label objects
  // Do major processing
  process.processMessages();
 // Do major processing.
  process.processMessages();
 // ...
}
```

The initial setTimeout is required; because apparently the screen/activity hasn't fully been displayed or and/or the activity messageloop hasn't been primed or something -- Not sure what it is.  If I just call the startProcessing() without tossing it off in a setTimeout; the screen just shows blank white the entire time...

The process.processMessages() is the function I modified from @atanasovg suggestions and it will show up in my opensource nativescript-master-technology plugin when I have a chance to release it.   

And yes it is a very hacky way of doing it; but based on everything I've researched and messing with several variations of the code; I think it is the only way to do it from JS currently.

The better solution for this feature would be to add a synchronous processMessages function to the runtime that would leave the vm; post a NS_RESUME_VM message to the end of the messageloop. And then drop into the message loop to allow all the message loop messages to be handled; once that message is received it jumps back into the vm as if returning from the processMessages function.  Sounds simple enough, but I haven't played with either runtimes message loop code so I couldn't really say.

**Comment by x4080** [comment]
in your startprocessing, basically you split the big processes into smaller processes, update the display and do other next process?

can we just update the display then settimeout for the next process? Or theres something that different?

**Comment by NathanaelA** [comment]
Basically if I understand you correctly yes the format was something like this:

```
label.text = "Opening Database...";  
progress.value++;  
process.processMessages();
// code to open database...

label.text = "Checking for updates...";
progress.value++;
process.processMessages();
// Code that checks for updates.

// Etc...
```

However, since that point I've benchmarked using the processMessages vs setTimeout and setTimeout(function,0) actually is faster.  So since processMessages is hacky and already has to use a short interval setTimeout it is not the best solution in my mind unless you absolutely need a synchronous code method.

In my case I was already using promise based code so I just created a status update function that returns a promise and now my status code is:

```
function updateStatus(msg) {
return new Promise(function (resolve) {
  label.text = msg;
  progress.value = progress.value + 1;
  setImmediate(resolve);
});
}
```

So I just do 

```
 updateStatus('doing work')
.then(dowork)
.then(updateStatus('more work'))
.then(domorework)
.then(updateStatus('and more work'))
.... more updates and more work. ...
```

Does that help?

**Comment by x4080** [comment]
Yes that's what I thought also, we still need background thread :)
How about the ios version though ? I read briefly it related to background process maybe I'm wrong though

**Comment by NathanaelA** [comment]
On iOS; not sure haven't tested it -- speed wise; it probably is faster -- I'll check at some point in the future of the speed just to see.  But the iOS code isn't dealing with a background thread; it is basically a mostly direct method to process the messages on the main thread.  Where @atanasovg android code is rather brilliant, it is very hacky and might break easily in a new version of the OS.

As for background threads; oh yeah.  That is probably my biggest feature I'm feel NativeScript is missing.  Personally I would put it before Windows Mobile support...

**Comment by x4080** [comment]
+1 for background thread :)
