### ISSUE TITLE
LiveEdit Research

### ISSUE THREAD

**Issue by KristinaKoeva** [NativeScript/ios-runtime#499]
We should make a research whether it is possible to perform JavaScript live sync without restarting the application.

**Comment by KristinaKoeva** [comment]
**Communication**

The easiest way to communicate a change in a JavaScript file to the runtime is through the debugging channel. We already have an established connection that uses the debugging protocol so we may reuse it. 
When we execute live edit command from Terminal, CLI should open a connection to 18181 port. When a JavaScript file is modified, CLI should send a [Debugger.setScriptSource](https://developer.chrome.com/devtools/docs/protocol/1.1/debugger#command-setScriptSource) json message that would contain the modified content. Debugger.setScriptSource requires an integer that represents the identifier of the changed script. All script identifiers are received through Debugger.scriptParsed so when a connection is opened CLI should start listenning for those messages and record a map of identifier/file path. 

**Runtime Implementation**

1. _[Could be done later]_ Currently the debugger communication goes through a single hardcoded port. This means that it would be really hard (or impossible) to have an attached debugger and a live edit session at the same time. https://github.com/NativeScript/ios-runtime/issues/511
1. Extend [Debugger.json](https://github.com/WebKit/webkit/blob/master/Source/JavaScriptCore/inspector/protocol/Debugger.json) with a Debugger.setScriptSource message.
1. Change the diff algorithm that is used in v8 so that it could fit into our needs. The diff algorithm would then tell us how lines/columns has changes so that we could update only the function exectables that are changed
1. Add a [custom source provider](https://github.com/NativeScript/ios-runtime/commit/8b5973b04f0ad4c8b9f11260f9c5eeb8d3f2c0c1#diff-e2744999e132f02c6f60f23095e55292R4) that would derive from ```JSC::SourceProvider``` but would have the ability to modify its source.  When a Debugger.setScriptSource message is received we could find the exact module with the specific source id and change its source content through our custom source provider to the new source content (e.g. https://github.com/NativeScript/ios-runtime/commit/8b5973b04f0ad4c8b9f11260f9c5eeb8d3f2c0c1#diff-24027070357654805883c7fbd723a740R128)
1. When a Debugger.setScriptSource message is received we should iterate every cell and delete the code blocks of those JSFunction cells that are part of the changed file and are within the reported by the diff algorithm lines/columns. This would guarantee that the bytecode would be regenerated with the new content on next run. Those operations should be executed when the vm is idle, so this one should be fixed first https://github.com/NativeScript/ios-runtime/issues/521 (e.g. https://github.com/NativeScript/ios-runtime/commit/8b5973b04f0ad4c8b9f11260f9c5eeb8d3f2c0c1#diff-24027070357654805883c7fbd723a740R68)
1. We should also update every JSFunction cell SourceCode start line, start columnt, length etc with the values that are reported by the diff algorithm. The parser use this values so that it could determine where the function starts and ends. Currently those properties of SourceCode are read only, so we have to create setters. 

The Proof Of Concept code could be found [here](https://github.com/NativeScript/ios-runtime/compare/KristinaKoeva/LiveEditResearch)

**Comment by KristinaKoeva** [comment]
@NathanaelA you've also made a research on LiveEdit functionality for iOS (correct me if I am wrong). So it would be great if you share your opinion on the matter.

**Comment by NathanaelA** [comment]
@KristinaKoeva you are way past my research.  All I've done is looking into the JSC code base to figure things out a simple method to do this -- yours is way cooler and better.  :grinning:

On number 3; your using JSC on iOS not v8.   I think you had a typo...

One part of the implementation you might want to change/add though is:
1. Ask JSC if file is loaded; if not loaded transfer then just new copy up and skip the rest. 

Can the diff routine be in the debugger code on the client device; I know it wouldn't be as optimized; but the client actually has the "original" file -- at this moment unless you are transferring the original back from the device; the computer doesn't.  
So if your basic steps are:
1. Upload the new file
2. Debugger takes new file and does checks and diff
3. does rest of steps you outlined
4. Then REPLACES old file with new file (because you know if it crashes for unrelated reasons and I restart the app on the device; I expect to be exactly where I was code wise on the device.

I love where you are going with this.

**Comment by KristinaKoeva** [comment]
Take a look for the initial version here https://github.com/NativeScript/ios-runtime/pull/614
For more information follow this issue https://github.com/NativeScript/ios-runtime/issues/649
