### ISSUE TITLE
Debugger without tns CLI

### ISSUE THREAD

**Issue by bolismauro** [NativeScript/ios-runtime#518]
Hello Everyone,

I'm developing a library that uses the NativeScript ios-runtime.
I don't need the the layer that has been built on top (e.g., views, layout ...) and therefore I won't use the tns CLI tool.
I've create a project that basically leverage the ios-runtime to run some JS scripts.

The way in which I've debugged these scripts is by using `console.log`
statements but it is becoming more and more unmanageable.
Since my knowledge about tns CLI is very limited I'd like to understand from you if there is a way to run the debugger (either in Safari or in the Native Script inspector) without using the tns CLI.

Thank you very much!
Mauro

**Comment by KristinaKoeva** [comment]
Hey Mauro,

First of all if you are not going to use the command line tool I suspect that you are not going to use the default project template either. So in order to debug your application please make sure that you've included the [TNSDebugging.h](https://github.com/NativeScript/ios-runtime/blob/master/src/debugging/TNSDebugging.h). This header file (among other things) setups the communication channel required in order to attach the [NativeScript AppInspector](https://docs.nativescript.org/runtimes/ios/how-to/AppInspector) to your application. It's main entry point is the [TNSEnableRemoteInspector](https://github.com/NativeScript/ios-runtime/blob/master/src/debugging/TNSDebugging.h#L168) method so call it before you call the ```[runtime executeModule:@"./"];```. We've done the exact same thing in our [template project](https://github.com/NativeScript/ios-runtime/blob/master/build/project-template/internal/main.m#L49) so you could use it for guidance. 

Then follow the steps:

1.  Pass the ```--nativescript-debug-brk``` environment varibale to instruct your application that it should wait for a debugger before executing anything.
1. Download the NativeScript AppInspector application available as a [npm package](https://www.npmjs.com/package/tns-ios-inspector). 
1. Deploy your application on an iOS Simulator/Device. In order to debug an application on an iOS Device you should forward the 18181 debugging port from your localhost to device. Usbmux (available as a [npm package](https://www.npmjs.com/package/usbmux)) has a useful tool called _iproxy_ that allows you to forward localhost ports to the device. Once installed you should just type the following command in your Terminal window
```iproxy 18181 18181``` . 
1. To open the NativeScript AppInspector application execute the following command in your Terminal window ```open [path to installed inspector package]/NativeScript Inspector.app --args [path to installed inspector package]/WebInspectorUI/Main.html Title```. On my machine this command looks like this 
``` open node_modules/tns-ios-inspector/NativeScript\ Inspector.app --args node_modules/tns-ios-inspector/WebInspectorUI/Main.html Title ```

Hope this helps,
Kristina

**Comment by bolismauro** [comment]
Hi!
Thanks for your help, I managed to have a working debugger following your instructions.
Unfortunately I've encountered another problem..
My javascript file, let's call it `app.js`, is created starting from different javascript files. 
The AppInspector obliviously shows the source code as a single file and it is quiet hard to debug and find functions.

I'm trying to leverage source maps to avoid this problem, but it seems that the AppInspector is not able to load them.

I've dug in the AppInspector source code and it seems that the `SourceMapManager` tries to load the source map (`app.js.map`) but the function `NetworkAgent.loadResource(frameIdentifier, sourceMapURL, sourceMapLoaded.bind(this));` fails to to that.
The error the callback receives is 
```
'Network' domain was not found
```

I honestly don't have any idea on how I can fix this or if source maps are supported at all in this context.

Thanks again!
Mauro

**Comment by KristinaKoeva** [comment]
Hey,

The communication between the runtime and the inspector frontend is divided into number of domains. We have implemented some of the domains, like the Page domain that is responsible for the content of your application files. So every ```Page.getResourceContent``` call goes directly to the runtime and returns the right content of the file.
The Network domain is not yet implemented in the runtime. We have decided that the implementation of the Network domain should be shared among the iOS and Android runtimes, so we are trying to move its functionality from the runtimes to the NativeScript modules. You could take a look at [this branch](https://github.com/NativeScript/NativeScript/tree/KristinaKoeva/NetworkSpike) for reference. The idea behind it is that you could register a domain dispatcher that would handle every call for that specific domain. So when you register a Network domain you would be the one responsible for handling the loadResource method. Since this is still work in progress and is going to change over time I suggest you wait for the official version and then we could figure out a way to support your scenario without the necessity of having Native Script modules.
There is also an option to modify the iOS runtime and register a native Network domain but I really don't recommend this approach.

Regards,
Kristina

**Comment by bolismauro** [comment]
Thank you for your answer!
Everything is crystal clear now. I have one more question for you: Is there any ETA for the implementation of this Network module?
Maybe starting from your implementation we can figure out a way to make it work also in our scenario

Thank you

**Comment by KristinaKoeva** [comment]
We've just merged a runtime implementation for the source maps. Take a look at #525 .
Bare in mind that this is not tested yet and will be officially released with our 1.7 release expected later this month

**Comment by bolismauro** [comment]
Sorry for the very late answer but I've had the chance to test this only today.

So basically I've updated my  `tns-ios` to version `1.7.0`.
I've followed the steps and the debugger works as expected with the exception of the source maps.

My ObjC code is the following
```objc
        extern char startOfMetadataSection __asm("section$start$__DATA$__TNSMetadata");
        
        // You need to call this method only once in your app.
        [TNSRuntime initializeMetadata:&startOfMetadataSection];
        [TNSRuntimeInspector setLogsToSystemConsole:YES];
        
        // Tell NativeScript where to look for the app folder. Its existence is optional, though.
        runtime = [[TNSRuntime alloc] initWithApplicationPath:[[NSBundle mainBundle] bundlePath]];
        
        // Schedule the runtime on the runloop of the thread you'd like promises and other microtasks to run on.
        [runtime scheduleInRunLoop:[NSRunLoop currentRunLoop] forMode:NSRunLoopCommonModes];
        
        TNSEnableRemoteInspector(argc, argv);
        // Run main file
        [runtime executeModule:@"../bundle.js"];
```

While here you can find the bundle.js, with a test js code, and the source map
https://gist.github.com/bolismauro/9c5cda21e7630749016c
the sourcemap is located in the same folder of the javascript file.

I can debug the code but the inspector shows it without applying the source maps.
I also tried to embed source maps in the bundle.js directly but nothing has changed.

I don't know it this can be useful: In the resources tab of the inspector I see two folders: app, which is empty, and Extra Scripts, which contains `bundle.js` and nothing else.

Let me know how can I help you in understand this behaviour!
Many Thanks

**Comment by KristinaKoeva** [comment]
Hey,

The NativeScript Application source code resides in the app folder and the debugger enumerates all resources that are within that folder. Later when the debugger frontend asks for a particular resource - your source map for example - the backend implementation goes through all the resources that have already been enumerated and returns a resource content if it exists.
So I suggest you move your application code in the app folder.
