### ISSUE TITLE
WebKit submodule

### ISSUE THREAD

**Issue by bolismauro** [NativeScript/ios-runtime#522]
Hello,
I was looking at the iOS runtime source code and I noticed that there is a submodule of webkit.
I have some questions regarding this:

1. Why do you do this?

2. Do you use the iOS built-in JSCore to execute the JS code or do you use a different, modified version? If you use a different version, why do you do that? What are the differences with the system one?

3. Apple PLA (...) say that

> 3.3.2 Except as set forth in the next paragraph, an Application may not download or install executable code. Interpreted code may only be used in an Application if all scripts, code and interpreters are packaged in the Application and not downloaded. The only exceptions to the foregoing are scripts and code downloaded and run by Apple's built-in WebKit framework or JavascriptCore, provided that such scripts and code do not change the primary purpose of the Application by providing features or functionality that are inconsistent with the intended and advertised purpose of the Application as submitted to the App Store.

The important part here is that only the built-in framework is allowed.
Is Native Script compliant with this point?

Thank you,
Mauro

**Comment by fealebenpae** [comment]
We use a custom-built JavaScriptCore, not the built-in one. The main reason is that the APIs we need to build the runtime and the Objective-C bridge are internal to JavaScriptCore and are thus considered private iOS APIs. We circumvent this by bundling our own build of JavaScriptCore.

A nice side-effect of this is that NativeScript apps always get the same JavaScript features and behavior, regardless of the iOS version they run on. We usually track WebKit's bleeding edge, so our version of JavaScriptCore is newer than the one in iOS 9. Most of the changes in our fork of WebKit are done so that we can build JavaScriptCore as a static library and without using private APIs.

We are aware of the limits stipulated by 3.3.2 and we believe we are in full compliance as all the JavaScript code interpreted by the runtime is bundled in the application package, as only the built-in JavaScriptCore is allowed to execute code downloaded after the app has been installed.

**Comment by bolismauro** [comment]
Thank you for your quick answer!
Do you think it is possible to achieve the same goal without using a custom version of JS Core?

**Comment by fealebenpae** [comment]
Our first initial prototypes of the runtime used the built-in JavaScriptCore and only the public API, but the performance and overhead were unacceptable for what we wanted to achieve. It's doable, but it won't work as well, IMO. And even if that worked, you'd only be able to use the feature set of the JavaScriptCore in the oldest iOS you support, so stuff like ArrayBuffers, Promises, Reflect, arrow functions, various other ECMAScript 6 features would be potentially unusable, and you'd have to rely on transpilation and polyfils, just like on the web.

**Comment by bolismauro** [comment]
Alright, thank you for the clarification!
