### ISSUE TITLE
Cannot marshal JSON object to NSDictionary and vice versa 

### ISSUE THREAD

**Issue by karaahmed** [NativeScript/ios-runtime#54]
In Cordova one can call native APIs with JSON objects and they are converted to NSDictionary under the hood.
Consider the same behaviour for JSONArray <-> NSArray

**Comment by fealebenpae** [comment]
Right now the bridge will convert an Array to an NSArray implicitly, but that's because I can recognize the Array exotic object. I can project the Map exotic object as NSDictionary the same way, but from what I gather Maps are not what you're after.

Type-coercing exotic objects is simple, but it becomes tricky to do correctly for plain JavaScript objects. I can't guess the purpose of an object - is it array-like, is it map-like, is it javascript-framework-du-jour's idea of a date, and so on. That's why there's no implicit conversion to NSDictionary today.

What I can do is convert an Object to a NSDictionary only when the target type is explicitly NSDictionary. That is to say, if a native function or method accepts CFDictionaryRef or NSDictionary. Would that work for you?

**Comment by fealebenpae** [comment]
The runtime can now wrap JavaScript values in `NSArray` and `NSDictionary` instances:
 - When converting to `id`
  - Values of the JavaScript `Array` exotic object will be wrapped as `NSArray`
  - Values of the JavaScript `Map` exotic object will be wrapped as `NSDictionary`
 - When converting to `NSArray` or `NSDictionary`
  - Values of the JavaScript `Array` exotic object and plain JavaScript objects with a `length` property and indexed properties will be wrapped as `NSArray`
  - Values of the JavaScript `Map` exotic object and plain JavaScript objects will be wrapped as `NSDictionary`

Native `NSArray` and `NSDictionary` instances will still be exposed as Wrapper exotic objects to JavaScript, same as before.
