### ISSUE TITLE
Variable WCSession not defined {N} 1.7.0

### ISSUE THREAD

**Issue by enchev** [NativeScript/ios-runtime#541]
_From @Milewski on March 30, 2016 10:20_

i'm trying to share data between iPhone and iWatch but i am not able to get [WCSession](https://developer.apple.com/library/ios/documentation/WatchConnectivity/Reference/WCSession_class/). it always returns me as null and crash whenever i try to access it..

here is the code i'm trying to execute:

```
if (!application.ios) return;

 if (WCSession.isSupported()) {
   var session = WCSession.defaultSession();
   session.delegate = this;
   session.activateSession();
}
```
Error
```
ReferenceError: Can't find variable: WCSession
```

Theoretically it should be a global object or as WCSession or NSObject.WCSession isn't it?

_Copied from original issue: NativeScript/NativeScript#1866_

**Comment by ivanbuhov** [comment]
Hi @Milewski
[WCSession](https://developer.apple.com/library/ios/documentation/WatchConnectivity/Reference/WCSession_class/) is available in iOS 9.0 and later,
<img width="729" alt="wcsession" src="https://cloud.githubusercontent.com/assets/2405533/14141521/32846b90-f688-11e5-821d-cc0035e73b0e.png">

which means it is `undefined` when the app is running on a device with older iOS version. Bare in mind that the class is not present not only in the JavaScript side but in the native, too, so if you were writing a native app and targeting iOS version older that 9.0 you should check for the existence of `WCSession` at runtime:
```
if ([WCSession class]) {
  // iOS 9.0 or later
}
else {
  // iOS 8 fallback
}
```
In the context of NativeScript you can perform the same check like this:
```
if (WCSession) {
  // iOS 9.0 or later
}
else {
  // iOS 8 fallback
}
```

**Comment by Milewski** [comment]
@ivanbuhov 
indeed i should be checking for the existence of WCSession first, however the version I'm running is 9.2 ~ 9.3 on a simulator iPhone 6 plus and this is coming as undefined. 

if i was to make it purely on Xcode using swift language for example i would need to import WatchConnectivity at the top of my class.. how could i handle this import using nativescript?

**Comment by ivanbuhov** [comment]
@Milewski 
I built an app with Xcode 7.3 against iOS 9.3 SDK and now I can see the problem. The metadata generator fails generating metadata for most of the types in `WatchConnectivity` framework. This comes from a change introduced in iOS 9.3 SDK - all availability macros are used with different version format:
```
// iOS 9.3 SDK
NS_CLASS_AVAILABLE_IOS(9.0)
__IOS_AVAILABLE(9.3)
``` 
```
// iOS 9.1 SDK
NS_CLASS_AVAILABLE_IOS(9_0)
__IOS_AVAILABLE(9_1)
```
These version arguments are eventually prepended with `__IPHONE_` and the result is expected to be an existing macro defined in `Availability.h`:
```
// Availability.h
#define __IPHONE_9_1      90100
#define __IPHONE_9_2      90200
#define __IPHONE_9_3      90300
```
but since there is no `__IPHONE_9.3`, `__IPHONE_9.1` etc. macros defined the clang compiler (which is embedded in the metadata generator) fails. Not only there are no such macros but I can't define them because the dot character (`.`) is not allowed to be in macro identifier. As a result all definitions decorated with such an attribute are skipped. The interesting part is that `WatchConnectivity` is the only place where the version format has changed. In all other SDK frameworks the underscore is used as version delimiter (`9_0`, `9_1` etc.).

You can make it work by replacing the version format of all the headers in `WatchConnectivity` frameworks (`WCError.h`, `WCSession.h`, `WCSessionFile.h` and `WCSessionDictionaryTransfer.h`) to the old one. A simple find and replace (`9.` with `9_`) in the files will do the trick (tested). Bare in mind that changing the iOS SDK which is coming with Xcode is a workaround, not a permanent solution.

I didn't investigate the problem further, but I guess updating the clang version in metadata generator may fix the problem (not tested).

**Comment by Milewski** [comment]
It sounds hacky, 

I tried to sticky to the version 9.2 to see why (as you mention it is a problem only in the 9.3 naming), but it seems just started to work for me after i linked the WatchConnectivity.framework into the project.

![WatchConnectivity.framework Xcode](https://cloud.githubusercontent.com/assets/2874967/14163854/17166224-f72c-11e5-96ab-ed1d1b0a6cf6.png)

**Comment by ivanbuhov** [comment]
@Milewski 
Linking against `WatchConnectivity.framework` is not required. The iOS runtime will load the needed frameworks lazily at runtime when a symbol belonging to a given framework is used for first time.

**Comment by Milewski** [comment]
uhm... now i am facing the problem with WCSessionDelegate

iWatch 

```swift
import UIKit
import WatchKit
import WatchConnectivity

class ShowProductController: WKInterfaceController, WCSessionDelegate {
    
    var session:WCSession!
    
    override func awakeWithContext(context: AnyObject?) {
        
        super.awakeWithContext(context)
                
        if(WCSession.isSupported()){
            session = WCSession.defaultSession()
            session.delegate = self
            session.activateSession()
        }
        
        session.sendMessage(["response":"Hello iPhone"], replyHandler: nil, errorHandler: nil);
         
    }

    func session(session: WCSession, didReceiveMessage message: [String : AnyObject]) {
        print(message); // i get hello iWatch
    }
        
}

```

iOS (nativescript)
```javascript

if (!WCSession) return;

var Extended = WCSession.extend({
    didReceiveMessage: function (message) {
        console.log(message); // should receive Hello iPhone?
    }
    }, {
        protocols: [WCSessionDelegate]
    });

if (WCSession.isSupported()) {
    var session = ExtendedClass.defaultSession();
    session.delegate = Extended; // or ????
    session.activateSession();
    session.sendMessageReplyHandlerErrorHandler(['Hello iWatch'], null, null);
}
```
i am implementing the WCSessionDelegate wrongly?

**Comment by ivanbuhov** [comment]
Try with:
```
var MyWCSessionDelegate = NSObject.extend({
    sessionDidReceiveMessage: function (session, message) {
        console.log(message.message);
    }
}, { 
    name: "MyWCSessionDelegate",
    protocols: [WCSessionDelegate]
});

if (WCSession.isSupported()) {
    var session = WCSession.defaultSession();
    session.delegate = new MyWCSessionDelegate();
    session.activateSession();
    session.sendMessageReplyHandlerErrorHandler({ "message": "Hello iWatch!" }, null, null);
}
```
More detailed info you can find in the [Subclassing Objective-C Classes](https://docs.nativescript.org/runtimes/ios/how-to/ObjC-Subclassing) article.
