### ISSUE TITLE
Interpreting iOS release-crashlogs 

### ISSUE THREAD

**Issue by manijak** [NativeScript/ios-runtime#554]
This is more of a question rather than a direct issue. Since I've released my app to the AppStore I've received a few crash-reports directly to XCode. I would to find out what is causing these crashes but the logs are very cryptic and don't tell me anything useful. 

Are there any tips on how to find out the reason for the crash? There are some repeating patterns in the logs, like the exception type, EXC_BAD_ACCESS (SIGSEGV). I guess this is something like a "null pointer exception"? And it's always in "Tread 0".

But figuring out where it happens in the code seems like an impossible job right now...

**Comment by ivanbuhov** [comment]
@manijak The crash report is cryptic because it shows the native stack only, which is not so useful for a NativeScript developer because it is usually full of JavaScriptCore internal functions. We can't change the  native stack trace but we can think of a way to include the JavaScript stack trace in crash reports - it should be more helpful to app developers.

**Comment by manijak** [comment]
Yes, that would be great! :-)

But untill then, there is no easy way to find out what is causing the crashes?

**Comment by ivanbuhov** [comment]
Since the crash report doesn't consist of a stack trace only, you can take advantage of the useful information coming with the crash report such as device mode, iOS version etc. Also, you can still see all native method calls from the native call stack, which in some cases can be enough for identifying the problem. But I agree that in the case of a NativeScript application, the most useful aspect of a crash report would be a JavaScript call stack and currently there is no way to retrieve it.

**Comment by AntonioCuevaUrraco** [comment]
What I don't understand about this issue is why is it possible to see the JS stack trace and error on the console but not able to store them somewhere for later on after app is started again send it to some server. Is it some restriction build on iOS or is just that there have been no time/resources to do it?

**Comment by KristinaKoeva** [comment]
As @ivanbuhov said we all agree that JavaScript call stack in your Crash Report would be really valuable for {N} users. Unfortunately Apple Crash Reports are created by the system and we currently haven't found a way to extend the Crash Reports with a custom information (the aforementioned JavaScript call stack). 
The {N} runtime provides [onUncaughtError](https://docs.nativescript.org/api-reference/modules/_application_.html#onuncaughterror) callback to be used when an uncaught error occurs, so you can use a custom reporting solution (e.g. [Crashlytics](http://try.crashlytics.com/)) to log a JavaScript exception or some additional information.

**Comment by manijak** [comment]
Interesting that you should mention the 'onUncaughtErrorEvent' since I have this in my app:

```js
application.on(application.uncaughtErrorEvent, function (args) {
    if (args.android) {
        // For Android applications, args.android is an NativeScriptError.
        console.log("NativeScriptError: " + args.android);
        googleAnalytics.logException(args.android);
    } else if (args.ios) {
        // For iOS applications, args.ios is NativeScriptError.
        console.log("NativeScriptError: " + args.ios);
        googleAnalytics.logException(args.ios);
    }
});
```

I don't see anything in the console when the app crashes, but this is the only thing logged in GoogleAnalytics:
`NativeScriptException (@Runtime:callJSMethodNative:-2) {main}`

Are there any examples that show us how to use this and get the most useful exception message to log?

Thanks

**Comment by AntonioCuevaUrraco** [comment]
I am with @manijak how can you get the JS error information that is printed on console? is it accessible from the app? That would make really easy to send it to some service

**Comment by KristinaKoeva** [comment]
@manijak The ```googleAnalytics.logException``` is probably an asynchronious method so it is possible that the application exits before the logging is executed. This would explain why you only see ```NativeScriptException (@Runtime:callJSMethodNative:-2) {main}``` entry which is actually an exception entry that comes from the Android runtime. If this is the case you may try to persist the exception somewhere (e.g. file, local storage) and send it to analytics the next time the application is called

**Comment by manijak** [comment]
Ok that sounds reasonable. Is the above example that I posted a good way to log uncaught exceptions? I am looking for a property that would contain most of the information about the crash.

**Comment by KristinaKoeva** [comment]
The {N} modules have [tests](https://github.com/NativeScript/NativeScript/blob/b69680cbf3dda1be42b87d8e16a171f48d5c19c7/apps/ui-tests-app/app.ts#L71) that log exceptions in the exact same way, so I believe this is a great way to log uncaught exception.

**Comment by AntonioCuevaUrraco** [comment]
Thanks for the help @manijak and @KristinaKoeva

I just have one question, if I do on my app something like

```
make.crash();
```
On the uncaughtErrorEvent I get:
NativeScriptError: Error: The application crashed because of an uncaught exception. You can look at "stackTrace" or "nativeException" for more detailed information about the exception.

But on the mobile I see something much more detailed and useful in this situation:

````
....
ReferenceError: make is not defined
..... the file line and colum
the StackTrace
```
I am checking if I can get that to be send to a service, if I find the answer I will update here but if someone knows it would be great :-)

**Comment by manijak** [comment]
I've been also testing exception logging to Google-analytics, after the last release of our app this weekend, that runs on 2.0.1 we get the following in GA portal:

This is the list of exceptions that have occurred since the release. So it does log different types of exception, but I still cannot find a way to log the js stacktrace...
```
1.	NativeScriptException (@Runtime:callJSMethodNative:-2) {main}	
2.	ClassNotFoundException (@BaseDexClassLoader:findClass:56) {main}	
3.	IllegalStateException (@Request$Builder:build:458) {main}	
4.	NullPointerException (@Runtime:callJSMethod:712) {Thread-173760}
```

**Comment by AntonioCuevaUrraco** [comment]
I think the js stacktrace is simply, out of our hands to grab :-/ as @ivanbuhov says in his previous messages and it would have to be changed on the runtime itself. Correct me if I am wrong

And I hope now that NS is well stable this side but important issues can be taken into consideration :-)

**Comment by ivanbuhov** [comment]
In case of JS error you can use the `stack` property to retrieve the JS stacktrace and if you wish you can send it to google analytics.
```
application.on(application.uncaughtErrorEvent, function (args) {
    if (args.ios) {
        console.log("Stacktrace: " + args.ios.stack);
    }
});
```
Does this work for you?

**Comment by AntonioCuevaUrraco** [comment]
It works for me, the stack is what I was looking for 👍

**Comment by AntonioCuevaUrraco** [comment]
If someone is interested I ended up making a plugin for LogEntries to send the crash data https://github.com/AntonioCuevaUrraco/nativescript-logEntries
