### ISSUE TITLE
Vague error code 65 from xcodebuild

### ISSUE THREAD

**Issue by douglasstarnes** [NativeScript/ios-runtime#563]
I used the install script for Mac OS X to configure NativeScript and Android works just fine.  However, trying to run the bare bones app (`tns create`) crashes with iOS.  The emulator runs but the build fails with a vague error code of 65.  Here is the output of `tns run ios`:

```
Traceback (most recent call last):
  File "./metadata-generation-build-step", line 100, in <module>
    generate_metadata(arch)
  File "./metadata-generation-build-step", line 89, in generate_metadata
    error_file.write(error_stream_content)
TypeError: write() argument must be str, not bytes
Command /bin/sh failed with exit code 1

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution NativeScript\ PreBuild build/demo.build/Debug-iphonesimulator/demo.build/Script-C97FD7AC1ADE5369004DB2A4.sh
(1 failure)
Command xcodebuild failed with exit code 65
```

Where do I start looking for the problem in my configuration or is this a bug?  I'm using OS X 10.11.4, NativeScript 2.0.0, and Xcode 7.3.

**Comment by NathanaelA** [comment]
I worked with Douglas via Slack, and we determined the issue was line 89 of metadata-generation-build-step and he is running Python 3.5.1 -- apparently in Python 3.x the child process data is returned as bytes not a string.    So this code needs to be updated to check for bytes and/or version and/or to force it to be a string for anyone else that is running a later version of python.   At this moment we commented out 89 so that he can continue...

**Comment by douglasstarnes** [comment]
Also changing line 89 to `error_file.write(error_stream_content.decode('utf-8'))` will work.  To convert the bytes to a string just use the `decode()` method.  Thanks again for the help!
