### ISSUE TITLE
Integrating with 3rd party library; executing exposed `^blocks` and UI updates

### ISSUE THREAD

**Issue by christocracy** [NativeScript/ios-runtime#577]
Hi, I'm trying to integrate an existing 3rd party iOS framework with `NativeScript` into the default app with the `[TAP]` counter:

My framework exposes a number of blocks which can be registered, including:
```Obj-c
@property (copy) void (^locationChangedBlock) (CLLocation *location);
```
Within the framework, I execute these blocks on the main thread:
```Obj-c
if (self.locationChangedBlock) {
        dispatch_async(dispatch_get_main_queue(), ^{
            self.locationChangedBlock(location);
        });
    }
```

In `NativeScript`, I've got the data-binding under-control.  I have a bound `<Label [text]="location" class="message"></Label>`.  However, my bound-data does not update *within the block attached to my 3rd-party lib* -- it only updates, for example, if I manually engage the UI, for example by clicking the `[TAP]` button in the default app.

```Javascript
export class AppComponent {
    constructor() {
        var me = this;
        // Create an instance of my Framework.  Everything here is good; it works perfectly.
        // My 3rd-party lib is logging to XCode log as normal.
        var locationManager = new TSLocationManager();
        .
        .
        .
        locationManager.locationChangedBlock = function(location) {
            console.log('-Location Changed Block: ', location);  // <------- I see this
            // Bound <Label /> is not updating.
            me.location = location.timestamp;
        }  
    }
    .
    .
    .
};
```

Ideas?  It's as if my attached-blocks are not running on the UI thread.  I'm quite experienced with `Obj-c`.

**Comment by vakrilov** [comment]
The angular framework uses change detection + zone.js for updating bindings. The change detection is fired every time a task is executed inside the angular zone. Most async tasks (like events, `setTimeout()` call, promises, observables etc.) are automatically executed inside the angular zone so that change detection is triggered after they are done. However, NativeScript callbacks that come from the native are not - so this is probably the reason that your binding is not updated. 

One think you can try is: Inject `NgZone` in your application and wrap the code that handles the code of the callback inside zone.run() - this will trigger the change detection after the callback is finished.

**Comment by christocracy** [comment]
After updating to latest `NativeScript`, it seems to work now without `NgZone`.  Not sure, maybe I was scoped incorrectly.
