### ISSUE TITLE
Segmentation Fault: 11 - Plugin crashes on iOS

### ISSUE THREAD

**Issue by Merott** [NativeScript/ios-runtime#629]
This could be linked to #622, but since I don't know for sure and that one is closed anyway, I'm opening this issue...

I'm getting a Segmentation fault error on iOS, trying to upgrade my `nativescript-pdf-view` plugin, only when using a simulator with a 64-bit architecture.

I'm not sure at what point exactly the crash happens since there is no stack trace - only the Segmentation fault message:

```
com.apple.CoreSimulator.SimDevice.E0B5F5A2-42AC-4403-8CC5-D406D0AD355E.launchd_sim[23204] (UIKitApplication:com.merott.NativeScriptPDFViewDemo[0x95f8][23585]): Service exited due to signal: Segmentation fault: 11
```

I'm using `tns-ios@2.2.1`, iPhone 6 simulator on iOS 8.4.

To reproduce the issue, please clone the [`nativescript-pdf-view`](https://github.com/Merott/nativescript-pdf-view) repository and switch to the [`demo-crash`](https://github.com/Merott/nativescript-pdf-view/tree/demo-crash) branch, then run:

```
npm run demo:ios:crash

# OR manually:
npm install
cd demo
npm install
tns platform add ios
tns run ios
```

**Comment by jasssonpet** [comment]
Hey @Merott,

It seems that the problem comes from the [`new UIWebView(CGRectInfinite)`](https://github.com/Merott/nativescript-pdf-view/blob/864fd6ccfa58421ee0f7fe3864d2049ac61e94d4/src/plugin.ios.ts#L40) call. The `CGRect` structure uses `float` types on `x86` and `double` types on x86_64. If you try to do the same in a pure native app, the application will crash in a similar way. Changing this code to `new UIWebView(UIScreen.mainScreen().bounds)` seems to fix the issue.

**Comment by Merott** [comment]
Thank you @jasssonpet 

The only problem with that is that it seems to prevent view rotation when using `UIScreen.mainScreen().bounds`. I don't know why, but that's a different matter. As far as `ios-runtime` is concerned, this issue is resolved.

And thank you for the tip on the simulator crash logs. Definitely helpful!
