### ISSUE TITLE
iOS 10/XCode 8 Property extending/overridding in NativeScript

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/ios-runtime#662]
In iOS 9/XCode 7 everything was the class functions so overriding it was just a simple 
{ x: function(y) { /* blah */} } and x would be overridden on the new extended class.   

However with XCode 8 / iOS 10 -- I can't seem to find a way to override any of the (readonly) properties.  For example a ton of UIViewController items are now readonly properties instead of functions -- what is the proper way to override these?

For example:
https://developer.apple.com/reference/uikit/uiviewcontroller/1621419-shouldautorotate?language=objc

https://developer.apple.com/reference/uikit/uiviewcontroller/1621435-supportedinterfaceorientations?language=objc

https://developer.apple.com/reference/uikit/uiviewcontroller/1621438-preferredinterfaceorientationfor?language=objc

**Comment by ivanbuhov** [comment]
## Instance Properties
You can find an example of overriding instance properties [here](https://docs.nativescript.org/runtimes/ios/how-to/ObjC-Subclassing#calling-base-methods-Subclass). The syntax is:
```
var MyViewController = UIViewController.extend({
    get modalInPopover() { return this.super.modalInPopover; },
    set modalInPopover(x) { this.super.modalInPopover = x; }
}, {
    name: "MyViewController"
});
```

## Static Properties
As stated in the [limitations section](https://docs.nativescript.org/runtimes/ios/how-to/ObjC-Subclassing#limitations) you can override only instance methods/properties... but you still can "hide" the native class property by redefining it like this:
```
var Student = Person.extend({});

Object.defineProperty(Student, 'staticPropertyName', {
    get: function() {
        return Person.staticPropertyName + " Modified";
    },
    set: function(value) {
        Person.staticPropertyName = value;
    }
});
```
Keep in mind that this is still not really overriding the property because the new implementation will not be triggered if the property is accessed from native code.

**Comment by NathanaelA** [comment]
If I understand you correctly; this is a pretty significant limitation now.  

A huge number of methods are now read only properties in xcode 8 and if we can't override them in NS code that is a significant issue. 

 So basically as it stands now we cannot override any of the UIViewController properties which allows us to manage rotation, sizing and several other properties that are the only way to do some things in iOS.

@jasssonpet any work arounds that you can think of for modifing the autorotate value in the primary UIViewController or Navcontroller?

Any idea for a time line to fix this issue since xcode 8 has now a huge number of read only props that you are supposed to override to change functionality?

**Comment by ivanbuhov** [comment]
@NathanaelA All the properties you linked in your first comment are instance properties. You can override instance properties the way I described in my [previous comment](https://github.com/NativeScript/ios-runtime/issues/662#issuecomment-250427455). The fact that the properties are `readonly` makes no difference... you still can override their getter (they have no setter). Limitation exists only for class(aka static) properties . I believe the properties that handle rotation and sizing are also instance properties, so you can easily override them. In other words, the transformation of instance methods into instance properties is not an issue, because NativeScript supports overriding both of them.

**Comment by NathanaelA** [comment]
Thanks, I have added a pull request to the main core (https://github.com/NativeScript/NativeScript/pull/2827) make this a lot simpler in the future, as the UINavContoller is created when the frame is created which is at the start of the app; once it is created; it is too late to add any new prototype functions to it to override any functionality.  I have managed to find a hack around that will work in the meantime; but actually updating the prototype before it is created would be the best solution.
