### ISSUE TITLE
require('someFile.JSON') is caching on iOS

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/ios-runtime#680]
A require against a JSON file should not be cached; the file can be changed by other means; and if I use a require to make my life simpler, I expect the current data to be retrieved....

Please note, this is also inconsistent with the Android engine which is NOT caching it (the proper behavior).

**Comment by jasssonpet** [comment]
Hey, @NathanaelA,

Thanks for reporting this inconsistency. Before we can discuss it, can you confirm that we are talking about the following use case or can you give another example of it:
```javascript
var object = require('./test.json');
console.log(object["test-prop"]); // Android: "test-value"; iOS: "test-value"; Node: "test-value"

object["test-prop"] = "new-value";

var object = require('./test.json');
console.log(object["test-prop"]); // Android: "test-value"; iOS: "new-value"; Node: "new-value"
```
Where `test.json` is a file containing the simple object: `{  "test-prop": "test-value" }`.


Ping @NativeScript/android-runtime

**Comment by slavchev** [comment]
Hi @NathanaelA 

Again, thanks for reporting this inconsistency. It seems this is a regression in Android bridge. I [fixed it](https://github.com/NativeScript/android-runtime/commit/3dd6a1aaa1eb82b1add2d060686f92d6ae5b8213) and added a common iOS/Andorid unit test in order to prevent future regressions. The fix is already pushed in `master` and `release` branches.

As a side note, I would like to point that while current [CommonJS spec](http://wiki.commonjs.org/wiki/Modules/1.1) doesn't explicitly discuss loading JSON files it does discuss that modules should be cached. The Node.js implementation also caches required JSON files. I cannot comment whether this behavior is useful but at least it is expected for the majority of the community. I guess it's fine to require small JSON files, especially if they are treated as read-only data.

**Comment by NathanaelA** [comment]
@slavchev & @jasssonpet  - Ack; I don't want them to be cached!  That was my complaint that iOS caches it...   ;-(

```
// Original Data: {"someData": "NS Rocks"};
var data = require('some.json');
console.log(data.someData);  // outputs "NS Rocks"  <-- CORRECT

// manually change the some.json file using FS.writeText so the JSON file now says
// {"someData": "NS is cool"} on disk
var data = require('some.json');
console.log(data.someData);  // outputs "NS Rocks" <-- WRONG

```

I can manually load the file; and then JSON.parse it, but using Require is so much simpler.  ;-)

**Comment by slavchev** [comment]
@NathanaelA If I understand the issue correctly you are looking for a convenient one-liner to load JSON files. If so then we can collaborate around such feature and keep `require` functionality aligned with the specs and the common expectation.

**Comment by NathanaelA** [comment]
@slavchev It isn't a big issue for me; using readtext and json parse is extremely simple.    I have to admit it caching json seems like really backwards behavior...   Which is why I complained to THIS repo about it caching it and not to the android one where it was behaving "properly" in my opinion.   But if you guys prefer the caching behavior it is fine.   I just think it is unexpected behavior.  :-)

Oh and just because node does something wrong, doesn't mean you have to do something wrong -- if I load a really large json file; you realize because you are caching it; and you are then wasting lots of memory for no good reason, on a mobile device!
