### ISSUE TITLE
Interop.Reference / Pointer issue

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/ios-runtime#698]
I'm trying to convert the code:
```
struct utsname systemInfo;
uname(&systemInfo);
```

However, this seems to fail no matter which way I try; with either everything being null, or a crash of the runtimes.   

Tried:
```
var systemInfo = new utsname();
var ref = interop.Reference(systemInfo);
or
var ref = interop.Reference(utsname, interop.alloc(interop.sizeof(utsname)));
or
var ref = interop.Reference(utsname);  
or
var ref =  interop.Reference(utsname, systemInfo); 

uname(ref);
console.log("", ref.value.machine, systemInfo.machine);
```

```
var size = interop.sizeof(utsname); // = 40
var buffer = interop.alloc(size);
uname(buffer);
var value = new utsname(buffer);
console.log("", value.machine);
```

Any ideas how I can get the "machine" value out?

**Comment by jasssonpet** [comment]
Hey, @NathanaelA,

Here are the declarations of the types above:
```c
#define _SYS_NAMELEN 256

struct utsname {
    char    sysname[_SYS_NAMELEN];  /* [XSI] Name of OS */
    char    nodename[_SYS_NAMELEN]; /* [XSI] Name of this network node */
    char    release[_SYS_NAMELEN];  /* [XSI] Release level */
    char    version[_SYS_NAMELEN];  /* [XSI] Version level */
    char    machine[_SYS_NAMELEN];  /* [XSI] Hardware type */
};

int uname(struct utsname *);
```

As stated in the [limitations section of our docs](http://docs.nativescript.org/runtimes/ios/Limitations#limitations) marshalling structs with constant size array members aren't supported.

You can use the following workaround, if you'd like:
```javascript
var _SYS_NAMELEN = 256;
var buffer = interop.alloc(5 * _SYS_NAMELEN)
uname(buffer);

NSString.stringWithUTF8String(buffer.add(_SYS_NAMELEN * 0)).toString() // sysname
NSString.stringWithUTF8String(buffer.add(_SYS_NAMELEN * 1)).toString() // nodename
NSString.stringWithUTF8String(buffer.add(_SYS_NAMELEN * 2)).toString() // release
NSString.stringWithUTF8String(buffer.add(_SYS_NAMELEN * 3)).toString() // version
NSString.stringWithUTF8String(buffer.add(_SYS_NAMELEN * 4)).toString() // machine
```

**Comment by NathanaelA** [comment]
@jasssonpet - Thanks, this is an awesome example on how to bypass the fixed structure issue!    

Does a bug report need to be created to work on allowing the Meta generator to understand things like _SYS_NAMELEN is so that it can parse fixed and mixed structures?

**Comment by jasssonpet** [comment]
No need for a bug report, we have discussed the issue and have added it to our backlog.

**Comment by dartmann** [comment]
Sorry for reviving this old issue, but when I do this in TypeScript:
`NSString.stringWithUTF8String(buffer.add(_SYS_NAMELEN * 4)).toString();`
The following error is shown:
`TS2345:Argument of type 'Pointer' is not assignable to parameter of type 'string'`.

This is because [`Buffer#add`](https://docs.nativescript.org/angular/runtimes/ios/types/c-pointers#interoppointer) returns a new Pointer. And [`NSString#stringWithUTF8String`](https://developer.apple.com/documentation/foundation/nsstring/1497379-stringwithutf8string?preferredLanguage=occ) expects `const char *` which is interpreted as `string` on TS level (looking into objc!Foundation.d.ts).

I am sure this can be resolved but atm I am not able to do so. How can I get the value behind the Pointer (I am aware of the [`Reference`](https://docs.nativescript.org/angular/runtimes/ios/types/c-pointers#interopreference) interface but do not know if it could be of any help here)?
Could you help me out with an explanation of what I am doing wrong?
I appreciate any help, thank your very much.

Cordially, David

**Comment by tdermendjiev** [comment]
Hi @dartmann, as you pointed out TS complains because `stringWithUTF8String` expects `string` as a parameter. One way to workaround it is to cast the `pointer` to `any` and then `any` to `string`. This can be achieved using a function such as:

``function asString(str: any): string{
    return str;
}``


And then:

````
let string = NSString.stringWithUTF8String(asString(buffer.add(_SYS_NAMELEN * 4))).toString();

console.log(string);
````

will print the proper value.

**Comment by dartmann** [comment]
@tdermendjiev thank you for your helpful response. Thanks to upcast and downcast this works. For me it was simply not clear that I can do that.

**Comment by DeepakArora76** [comment]
I want to seek insight on the below code from some of the experts:

```JavaScript
 static deviceId(): string {
    let systemInfo = new interop.Reference<utsname>();
    uname(systemInfo);
    return NSString.stringWithUTF8String(systemInfo.value.machine).toString();
  }
```

Is it safe to call `new interop.Reference<utsname>();` ? or I have to do it the old way `interop.alloc(5 * _SYS_NAMELEN)` as described above by @ @jasssonpet ?

**Comment by mbektchiev** [comment]
Hi @DeepakArora76,
This is a very reasonable question to ask. As it turns out it is perfectly OK to call it this way. 

Initially, I thought that this shouldn't work as `new interop.Reference<utsname>();` will actually create a `nullptr` `Reference`; I expected the call to `uname` to crash when it attempts to write to it but actually the runtime handles such cases gracefully and replaces the `nullptr` with a pointer to a newly allocated memory block of just the right size (according to metadata). [Here's](https://github.com/NativeScript/ios-runtime/blob/ee54003faf969dfa2712898a2ecc0ee22750dcee/src/NativeScript/Marshalling/Reference/ReferenceTypeInstance.cpp#L40-L45) the exact piece of code which does that.

**Comment by DeepakArora76** [comment]
Hi @mbektchiev, 

Thanks so much for your insights — I appreciate you taking the time to share helpful resources on ios-runtime.

With NativeScript every day, I am learning and gaining invaluable experience, whether it´s iOS, Angular, Typescript, or Android.

Have a great day ahead.
