### ISSUE TITLE
NSObject return from Objective-C/Swift function has undefined properties 

### ISSUE THREAD

**Issue by xmlking** [NativeScript/ios-runtime#712]
**Problem:** `NSObject` return from Objective-C/Swift function has `undefined` properties until  we check it with  `instanceof` 
wonder if I am missing something or it is a known issue with `NativeScript`
> Here is an example 

**swift code**
```swift
@objc public class HeartRateData: NSObject  {
    public let heartRate:UInt
    public init(heartRate:UInt) {
        self.heartRate  = heartRate
    }
}

@objc(TestClass)
public class TestClass: NSObject {
    public func getSomething() -> HeartRateData{
        return HeartRateData(heartRate: 55)
    }
}
```

**generated Objective-C**
```Objective-C
SWIFT_CLASS("_TtC13TestClass13HeartRateData")
@interface HeartRateData 
@property (nonatomic, readonly) NSUInteger heartRate;
- (nonnull instancetype)initWithHeartRate:(NSUInteger)heartRate  OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("TestClass")
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (HeartRateData * _Nonnull)getSomething;
@end
```

**JavaScript/TypeScript**
```js
var testClass = new TestClass();
var data = testClass.getSomething()
// why undefined?
console.log(data.heartRate) // undefined 
// magic happens here...
console.log((data instanceof HeartRateData)) // true
// working as expected 
console.log(data.heartRate) // 55
```

**Comment by ivanbuhov** [comment]
@xmlking Help me with reproducing the issue. I guess the Swift code is part of a framework. Can you upload a pre-build version of the framework or give me a link where I can download it. If it is easier, you can upload an example app.

**Comment by xmlking** [comment]
The Swift code base is at https://github.com/xmlking/MicrosoftBand

if I don't do `instanceof` workaround , I will receiving `nulls` for short time from my Observable. 

NativeScript code that is using above  Swift Package. 
https://github.com/xmlking/nativescript-ngx-microsoftband/blob/446ed7bc5e13cc3d0973f55df70143416f35a85c/src/app/services/microsoftband.service.ios.ts#L116

**Comment by jlewallen** [comment]
I just ran into this and was wondering if there was more information on how to avoid it?

**Comment by mbektchiev** [comment]
Hi, Jacob. Thank you for bringing our attention to this issue. We'll investigate it and write back soon.

**Comment by mbektchiev** [comment]
The reason for the undefined properties of the Swift object is that due to a bug in the runtime, the metadata for the class cannot be found correctly and it is being casted to its base (in the original report `HeartRateData` becomes `NSObject`). 

If you happen to instantiate the class' constructor function before instances of it are returned to JS, this constructor function is cached and it can be correctly discovered, thus alleviating the issue. We will think for a fix to this issue but in the meantime there are two workarounds that we can suggest:

1. Instantiate the types you will be using early in your app/plugin's initialization logic (e.g. `const HeartRateDataProto = global.HeartRateData`). This should be enough to make it work.
1. Make the Swift classes used in JS have a human-readable assigned Objective-C name with the @objc attribute i.e. `@objc public class HeartRateData` becoming `@objc(<NAME>) public class HeartRateData` would do the trick. `<NAME>` can be any suitable Obj-C identifier (e.g. `HeartRateData`, `HeartRateDataSwift`, `MyLib_HeartRateData`, ...)

**Comment by jlewallen** [comment]
Thank you so much for the fast reply! Option 1 seems to work great, thanks so much for the reliable workaround. I'm surprised to hear that providing the Name in @objc results in different behavior, but then again I'm still very green in the ObjC/Swift area.

**Comment by mbektchiev** [comment]
> I'm surprised to hear that providing the Name in @objc results in different behavior, but then again I'm still very green in the ObjC/Swift area.

This is due to some of the specifics causing the issue. By default, the Swift class name becomes the mangled version of `SwiftModule.ClassName` and that's what causes metadata discovery failure. When you explicitly set a name in Objective-C then the JS name matches the native one and the runtime manages to discover it.
