### ISSUE TITLE
Should multiple runtimes on the main thread work with the debugger ?

### ISSUE THREAD

**Issue by jeduden** [NativeScript/ios-runtime#717]
I am currently trying figure out if the ios runtime code supports using multiple runtime instances on the main thread. it looks like the execution of the JS works. However, the debugger doesn't break on break-points in this scenario. 

Also, saw the discussions around webworker. Would the debugger be more stable if one of the runtimes on a different (non-ui) thread ?

**Comment by ivanbuhov** [comment]
@jeduden I am interested in what are you trying to achieve by running two runtime instances on the main thread. What is the problem you are trying to solve? How do you initialize the runtimes and which runtime instance do you pass to the  [`TNSEnableRemoteInspector(argc, argv, runtime);`](https://github.com/NativeScript/ios-runtime/blob/1eea4fa472c6f959f63036fb051b163e22b14d37/cmake/main.m#L22) method call?
We have never had an use case to run more than one runtime on the main thread so this scenario is never tested and we haven't actively tried to support it. However, since I can't think of some technical blocker, from technical perspective it should be feasible. Regarding the debugger, currently only one runtime can be debugged and this is the one passed to [`TNSEnableRemoteInspector(argc, argv, runtime);`](https://github.com/NativeScript/ios-runtime/blob/1eea4fa472c6f959f63036fb051b163e22b14d37/cmake/main.m#L22) method. It is possible to have more than one inspector connected to different debugging frontends and listening on different ports but this requires some effort in the runtime(s) side.
P.S. Currently debugging of worker threads is not supported but you still can debug the runtime running on the main thread.

**Comment by jeduden** [comment]
My use case: i have two different systems driven by javascript code. Conceptually, they are disconnected and in an alternative implementation I naturally used two separate JavaScriptCore instances. 

Since the systems are separate, the event when a reload of the code could happen is also different. I implemented the reload by just throwing away the vm and instantiating a new one.
If I serve both systems from the same vm, i need to take a better look at hot module replacement.

A bit more context why I am asking: 
I stumbled across a section in the code that uses a mapping between thread and vm.
But I didn't see any explicit docs about this topic:
- https://github.com/NativeScript/ios-runtime/blob/9f38cae76f598ab761066d9e139104f2a32b1035/src/NativeScript/TNSRuntime.mm#L50

If there is no technical blocker by design, I can continue with my current approach and see what I find.

**Comment by ivanbuhov** [comment]
@jeduden The mapping between threads and VMs is needed by our worker implementation. Each worker runs on a separate thread in a dedicated `TNSRuntime`. There are cases where a code block can be executed in more then one threads and it needs a reference to the runtime running on the current thread. This is why we have mapping between thread and vm. In your scenario this may need to be refactored a bit to support more than one runtime running on a single thread. Does this answer your question?

Do you have any progress with running 2 runtimes on the main thread? I am curious about what blockers you met and what changes you have made on the code base in order to support this scenario?

**Comment by jeduden** [comment]
@ivanbuhov i essentially stayed on the proven path by enabling the debugger only for one runtime. also tweaked the architecture. With the tweak in place, i can get can away with a single runtime for now.

**Comment by ivanbuhov** [comment]
@jeduden Nice!
Just to summarize:
Currently, we don't support using multiple runtimes on the main thread but it seems to be doable with some limitations:
 * using Workers may not work or crash.
 * No available support for debugging both runtimes
Since there are no enough use cases for this one, we are not planning any effort to polish the whole "2 runtimes on main thread" story. This is why I am closing the issue. If anyone wants to contribute on this or just has another opinion, feel free to reopen the issue.
