### ISSUE TITLE
How to use shared framework in NativeScript plugins?

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/ios-runtime#755]
_From @asultonov on April 25, 2017 9:59_

I couldn't find any example of using shared frameworks in NativeScript plugins. There are also questions on StackOverflow, Discourse and here, but no one useful answer.

And so, I have shared framework file which is called OggVorbis.framework and I put them in Platforms/iOS directory. I'm trying to use this framework thus:

    declare const OggVorbis: any;

    export class NSOggVorbis {
        private vorbis: any;

        constructor() {
            this.vorbis = OggVorbis;

            console.log(OggVorbis); // UNDEFINED
            console.log(this.vorbis); // UNDEFINED
            console.log(this.vorbis.convert); // UNDEFINED
        }

        log(msg: string): void {
            console.log(msg);
        }
    }

But as you can see, nothing in this.vorbis or OggVorbis. Can anyone tell me why? And how to use shared frameworks?

This is issue. Because people are unable to create own plugins and can't use NativeScript fully. Other people who have the same question: [one](https://discourse.nativescript.org/t/problems-integrating-shared-framework-with-module-modulemap-included/599), [two](http://stackoverflow.com/questions/37245722/how-to-load-a-framework-file-with-a-nativescript-plugin), [three](https://github.com/NativeScript/nativescript-angular/issues/542)...

_Copied from original issue: NativeScript/nativescript-angular#768_

**Comment by NickIliev** [comment]
Not sure about OggVorbis is either a static framework or not, but to verify that you can follow [these instructions](https://docs.nativescript.org/runtimes/ios/how-to/Use-Native-Libraries#static-frameworks). If the framework is static you should create **_module.modulemap_** file again a full description of this scenario is shown in the link above., Note that there are some limitations when working with static frameworks. For example **_only Objective-C APIs are exposed (no C functions and C constants) from static frameworks._**

Moving this issue to ios-runtime as it is not related to Angular.

**Comment by asultonov** [comment]
I think the framework is not statistic, because it has .modulemap file:

![Framework module.modulemap file](https://cloud.githubusercontent.com/assets/14216919/25382771/8018dfa2-29d2-11e7-970c-87d741656889.png)

**Comment by NickIliev** [comment]
@asultonov is the OggVorbis.framework public file which can be downloaded and tested on our side? I've tried to locate this framework but to no avail.

**Comment by asultonov** [comment]
@NickIliev, yes.

[OggVorbis.framework.zip](https://github.com/NativeScript/ios-runtime/files/957435/OggVorbis.framework.zip)

**Comment by ivanbuhov** [comment]
Hi @asultonov 
The `OggVorbis.framework` is a static framework. A [well known limitation](https://docs.nativescript.org/runtimes/ios/how-to/Use-Native-Libraries#static-libraries) is that all C symbols (C functions, C structs, C vars etc) that are part of a statically linked library/framework are not automatically exported. You can workaround the issue by explicitly listing all symbols you want to export from the static library in your `build.xcconfig` file. These flags will force the linker to export `ogg_sync_init`, `ogg_stream_init` and `ogg_stream_flush` functions:
```
OTHER_LDFLAGS = -Wl,-exported_symbol,_ogg_sync_init,-exported_symbol,_ogg_stream_init,-exported_symbol,_ogg_stream_flush
```
In case you want to expose just a few symbols in JS this is a viable option, otherwise - you have two options:
1. Rebuild the library as a shared one.
2. Create an ObjC-wrappers of the `OggVorbis` functionality that you want to use in your app and expose the wrapping APIs.
