### ISSUE TITLE
Handling Closures

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/ios-runtime#769]
I'm opening a separate issue for this... So how do I go about mapping swift closures in my plugins?

So like you can see here: https://auth0.com/docs/libraries/lock-ios/v2/configuration#configuring-lock-s-behavior ".withOptions"

Here is the actual source for that 
https://github.com/auth0/Lock.swift/blob/71a04034848ed45f9a85d4725cb4b2625685f4c8/Lock/Lock.swift#L167

Is there any way I can implement these?  I see no way to do this inspecting the debugger...

**Comment by ivanbuhov** [comment]
@sitefinitysteve 
Since the iOS Runtime provides bridging between JavaScript and Objective-C, Swift APIs that are not exposed to Objective-C are not consumable from JavaScript. A Swift API is exposed to Objective-C only if it is included in the [autogenerated Swift bridging header](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html). So, I guess that `withOptions` method is not included in the bridging header.

Swift closures are converted to Objective-C blocks as long as every type involved can be translated to Objective-C. In your case the `OptionBuildable` protocol which is part of the closure signature is not marked with `@objc` modifier which means that it is not exposed to Objective-C (and JavaScript). As a result the closure itself can't be projected to Objective-C.

**Comment by sitefinitysteve** [comment]
Okay, so this is good!  I will request though Auth0... closing since it's not a NS issue

**Comment by sitefinitysteve** [comment]
They responded over in the thread above, are they correct?  I feel like we can call swift just fine with that @objc header right?  It's just that it's not exposed to JS?  Can you either respond over there or provide me the details to make an informed response?

**Comment by ivanbuhov** [comment]
@sitefinitysteve Exposing Swift APIs to Obj-C is not always the same as adding `@objc` modifier in front of the the types names. Some Swift-specific features can't be translated to Objective-C - you can find more info [here](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html#//apple_ref/doc/uid/TP40014216-CH10-ID136). It seems that there are other technical reasons that stop the Auth0 guys of exposing the desired APIs to Objective-C.

**Comment by sitefinitysteve** [comment]
Okay so what you're saying is that Nativescript cannot properly expose this Pod?

**Comment by ivanbuhov** [comment]
@sitefinitysteve No. The desired Swift API is not exposed to Objective-C. This can be confirmed by checking the autogenerated Swift bridging header. I haven't done it because I can't find it in the Auth0 codebase, so this is still an assumption. NativeScript has no control over which Swift APIs are exposed to Objective-C. This is in the hands of the library authors. 
By skimming through the `Auth0` source I supposed that `OptionBuildable` protocol should be the reason why the API in question is not exposed but I believe the `Auth0` guys can give a more detailed answer.
