### ISSUE TITLE
Can't run ios app after update to 3.1.1

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/ios-runtime#776]
_From @gbonline on June 30, 2017 13:30_

Hi, I tried to update nativescript this morning, to the 3.1.1 version, and my angular app didn't run anymore, also a new project don't work with the error of `missing entitlements file`

I tried with the simply commands
```
tns create new2 --ng
cd new2
tns run ios
```

then It can't run with a trace like this:

```
Create product structure
/bin/mkdir -p /Users/nemesix/Sviluppo/NativeScript3/new2/platforms/ios/build/emulator/new2.app

ProcessProductPackaging "" build/new2.build/Debug-iphonesimulator/new2.build/new2.app.xcent
    cd /Users/nemesix/Sviluppo/NativeScript3/new2/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/lib/share/oracle/instantclient_12_1"
    builtin-productPackagingUtility -entitlements -format xml -o /Users/nemesix/Sviluppo/NativeScript3/new2/platforms/ios/build/new2.build/Debug-iphonesimulator/new2.build/new2.app.xcent
warning: Falling back to contents of entitlements file "new2.entitlements" because it was modified during the build process. Modifying the entitlements file during the build is unsupported.error: The file “new2.entitlements” couldn’t be opened because there is no such file.

** BUILD FAILED **


The following build commands failed:
	ProcessProductPackaging "" build/new2.build/Debug-iphonesimulator/new2.build/new2.app.xcent
(1 failure)
Unable to apply changes on device: D7FEB5F0-06BB-4EF8-B9E8-61ED4FAEA138. Error is: Command xcodebuild failed with exit code 65.
```

What can I do?

_Copied from original issue: NativeScript/NativeScript#4484_

**Comment by yavin5** [comment]
I have this problem now as well, and I don't know how to fix it.

**Comment by yavin5** [comment]
Why is this issue closed without any solution?

**Comment by NickIliev** [comment]
@yavin5 the issue was never closed but moved to this repository - however, we can not reproduce the issue on our side so any additional information available would be of great help.
DO you have all the prerequisites for working with nativeScript on your MAC (XCode, xcodeproj, CocoaPods y as listed [here](https://docs.nativescript.org/angular/start/ns-setup-os-x#system-requirements))

**Comment by ivanbuhov** [comment]
@gbonline @yavin5 I can't reproduce the issue. I tried with the following steps:
```
tns create new2 --ng
cd new2
tns run ios
```
Can you think of something that may help reproducing the issue e.g. using the latest beta of Xcode or some other tool.
I found similar issue in the Firebase plugin repo -> https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/333 but it seems that it is not the same because it requires using the Firebase plugin. 

I guess that the CLI build step cleans the `new2.entitlements` file and the build fails later because it can't find it. I assume that it is related to this one https://github.com/NativeScript/nativescript-cli/pull/2753 so I am moving the issue to the [nativescript-cli repo](https://github.com/NativeScript/nativescript-cli).

**Comment by ivanbuhov** [comment]
This issue was moved to NativeScript/nativescript-cli#2946

**Comment by yavin5** [comment]
Well, except you're assuming that I'm using the nativescript cli..  I'm using Angular Seed Advanced and writing an Angular 4 app with components that render on ios and android via Nativescript.  So this issue here is valid, and the one in nativescript-cli doesn't apply.  This issue shouldn't be closed, and you shouldn't just close them (especially with zero comment) when other people in the community are saying they have the problem.

**Comment by ivanbuhov** [comment]
@yavin5 
Currently, the only provided reproduction steps we have so far are those [provided](https://github.com/NativeScript/ios-runtime/issues/776#issue-240190161) by @gbonline:
```
tns create new2 --ng
cd new2
tns run ios
```
 These reproduction steps include NativeScript CLI usage. As I mentioned in my [previous comment](https://github.com/NativeScript/ios-runtime/issues/776#issuecomment-312841277), we can't reproduce the issue with the provided steps, so it will be very helpful if you describe other steps, no matter if CLI is used or not.

 > This issue shouldn't be closed, and you shouldn't just close them (especially with zero comment)

The issue is not closed, it is [moved to another repository](https://github.com/NativeScript/nativescript-cli/issues/2946).
Here is my comment, justifying the issue movement -> https://github.com/NativeScript/ios-runtime/issues/776#issuecomment-312841277.
