### ISSUE TITLE
[iOS] Missing ARKit properties

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/ios-runtime#836]
_From @andreacappadona17 on December 12, 2017 15:56_

I'm trying ARKit combined with Vision in a NativeScript app, but when I try to access some properties like `transform` from [ARCamera](https://developer.apple.com/documentation/arkit/arcamera).

Looking through the docs, I found out that 

>The following members can not be accessed from JavaScript:
>
> * Unions
> * Variadic Objective-C methods, function pointers, blocks
> * Structs with constant size array members
> * Vectors
> * Inline functions
> *  int64_t, uint64_t outside the [-2^53, 2^53] range
> *  long double, int128_t, uint128_t

Is there no way to bypass this limitation? Am I doing something wrong?

Thanks

_Copied from original issue: NativeScript/NativeScript#5164_

**Comment by andreacappadona17** [comment]
Still nothing on this?

**Comment by NathanaelA** [comment]
Please note #558 is also blocked because of lack of union support.    Despite what @PanayotCankov says in that bug report.  I've been playing with opengl in NativeScript and it is actually missing pretty much all Matrix math functions which eliminates a the majority of your ability to do anything in NativeScript with openGL.    At this point, until matrix math can be supported -- if you need openGL, NativeScript is completely the wrong solution.  ;-(

**Comment by NathanaelA** [comment]
@andreacappadona17 - The only way to get around those limitations currently in NativeScript is to go 100% native, ObjC/Swift code for your openGL/ARkit stuff.   I've done it using a cocoapod helper that I call into that does any "heavy" lifting.     In most cases you can't even pass back the values back into NativeScript properly because it doesn't understand unions or fixed aligned structures.  So it really is a hack to make NS work in this area.  ;-(

For example I created my own matrix math class; rather than it passing back the matrix structure; it keeps it in its class memory.  So then when I call some matrix math function; it uses its existing copy.   At the point I need to assign it to another class; I call a "assignment" function that does that too.  Very painful, and requires a LOT of ObjC code...

**Comment by ginev** [comment]
@NathanaelA, @andreacappadona17 - we're currently working on supporting matrices exposed by the ARKit APIs. We've done most of the work but there are some niggles that prevent us from merging into master. I hope that we will be able to make some progress in the upcoming weeks.

**Comment by Natalia-Hristova** [comment]
This is implemented and will be available in the next official release of `ios-runtime`. You can test it out before that using tag `next` --> `tns platform add ios@next`
