### ISSUE TITLE
Interop.Pointer int64 creation from NativeScript side

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/ios-runtime#921]
### Please, provide the following version numbers that your issue occurs with:
3.4.x  (Probably 4.x also)

### Is there any code involved? 
var x = new Interop.Pointer(-1) =  `<Pointer: 0xffffffff>`
However, returning a pointer from ObjC of -1 = `<Pointer: 0xffffffffffffffff>`

Is their some secret to create a Interop.Pointer on the Javascript side that is the full int64 size, as it is a special value in a plugin I'm working on.   This is the only piece that I'm having to create a tiny OBJC wrapper for; and I would like to eliminate this wrapper if possible.

**Comment by charsleysa** [comment]
@NathanaelA looks like they are using 32bit transformations behind the scenes.
https://github.com/NativeScript/ios-runtime/blob/9d967a09370bee938b5f8a16f9b41bbc696555ab/src/NativeScript/Marshalling/Pointer/PointerPrototype.cpp

At this point I don't think you'll be able to create 64bit pointers from JS.

**Comment by NathanaelA** [comment]
@charsleysa - Stefan, yeah that was my determination also.    Hence this issue to hopefully have them create a new `Interop.Pointer64` method to do so. :grinning:

**Comment by mbektchiev** [comment]
I tested and it seems that now you can create a pointer from a 64bit number. 
```JS
console.log(new interop.Pointer(-2));
console.log(new interop.Pointer(-1));
```
Outputs:
```
CONSOLE LOG file:///app/index.js:5:12: <Pointer: 0xfffffffffffffffe>
CONSOLE LOG file:///app/index.js:6:12: <Pointer: 0xffffffffffffffff>
```

I found another issue, however -- `-1` turned out to be a special value for deleted keys in the [JSC::WeakGCMap](https://github.com/NativeScript/ios-runtime/blob/master/src/NativeScript/Interop.h#L90) that we're using and causes an assertion failure in debug builds of the runtime. Meaning that it still is not completely safe, regardless that it appears to work. I plan to fix it this week.
