### ISSUE TITLE
Incorrect Typings generation

### ISSUE THREAD

**Issue by aaayushsingh** [NativeScript/ios-runtime#974]
issue with Nativescript/ios-metadata-generator

When generating typings for a podfile, incorrect typings generated.

eg: for
```
- (BOOL)connectWithClientId:(NSString *)clientId
               cleanSession:(BOOL)cleanSession
              certificateId:(NSString *)certificateId
             statusCallback:(void (^)(Status status))callback;
```

the generated typing is 
```
connectWithClientIdCleanSessionCertificateIdStatusCallback(clientId: string, cleanSession: boolean, certificateId: string, callback: (p1: AWSIoTMQTTStatus) => void): boolean;
```

expected typing 

```
connectWithClientId(clientId: string, cleanSession: boolean, certificateId: string, callback: (p1: AWSIoTMQTTStatus) => void): boolean;

```

**Comment by NickIliev** [comment]
@aaayushsingh the output is expected due to the NativeScript's marshaling rules (data conversion from Objective-C to JavaScript). The rules are that any Objective-C methods will be converted to JS by concatenating the main method name with the required parameters.

For example, take a look [at this method](https://developer.apple.com/documentation/foundation/nsfilemanager/1410277-fileexistsatpath?language=objc)

Objective-C code
```Objectictive-C
- (BOOL)fileExistsAtPath:(NSString *)path 
             isDirectory:(BOOL *)isDirectory;
```

To use the above in NativeScript the converted JavaScript will look like this
```JavaScript
fileExistsAtPathIsDirectory("/some/dir", true);
```


More about marshalling rules ca nbe found [here](https://docs.nativescript.org/core-concepts/ios-runtime/Marshalling-Overview). So follwing the above rules the generated JS should indeed be `connectWithClientIdCleanSessionCertificateIdStatusCallback`
