### ISSUE TITLE
Unable to override objc exported swift method

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/ios-runtime#985]
### If there is no issue for your problem, tell us about it
I'm trying to override the following method in a project:
https://github.com/PeterStaev/folding-cell/blob/8777fc44100b9feb7a68c4536bd3f211cc2eab11/FoldingCell/FoldingCell/FoldingCell.swift#L284-L286
I've decorated both the method and the enum with `@objc`, this made both of them appear in the generated `.d.ts` file. But subclassing `FoldingCell` in the project and then trying to override the generated `animationDurationType` method has no effect. The method is never called and instead the superclass method is being called. 

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.2
- Cross-platform modules: 4.2
- Runtime(s): 4.2

**Comment by mbektchiev** [comment]
Hi @PeterStaev! Thank you for reporting this issue. I managed to reproduce it and investigated it. The reason for not being able to override the method is that Swift calls it using direct dispatch (for more info you can read [this awesome article on the kinds of method dispatch that Swift supports](https://www.raizlabs.com/dev/2016/12/swift-method-dispatch/). In order to make it call into the JS overridden method all you need is to declare the method `dynamic`. In this case:
```swift
    @objc open dynamic func animationDuration(_ itemIndex: NSInteger, type: AnimationType) -> TimeInterval
```

**Comment by PeterStaev** [comment]
Hey @mbektchiev , I can confirm that marking it with `dynamic` does the trick 🎉 Thanks for troubleshooting this. Might be a good idea to add this to the docs in case anyone else stumbles on this 😉
